<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Helper\Sample;

class Pelanggaran extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Siswa_model');
        $this->load->model('Kategori_model');
        $this->load->model('Pelanggaran_pengasuhan_model');

        // cek user login
        check_login();
    }

    /*
     * Listing of siswa
     */
    function index()
    {
        $data['siswa'] = $this->Siswa_model->get_aktif_siswa();

        $data['_view'] = 'pelanggaran/index';

        $this->load->view('template/header', $data);
        $this->load->view('template/sidebar', $data);
        $this->load->view('pelanggaran/index', $data);
        $this->load->view('template/footer', $data);
    }


    function detail ($id)
    {
        // periksa bahwa data santri itu ada
        $data['siswa'] = $this->Siswa_model->get_siswa($id);

        if (isset($data['siswa']['id'])) {
                $data['datafilter'] =$this->Pelanggaran_pengasuhan_model->filter_by_id_siswa($id);
                $data['detail'] =$this->Siswa_model->detail_data($id);
               
                $data['_view'] = 'pelanggaran/detail';
                $this->load->view('template/header', $data);
                $this->load->view('template/sidebar', $data);
                $this->load->view('pelanggaran/detail', $data);
                $this->load->view('template/footer', $data);
        } else
        show_error('The siswa you are trying to edit does not exist.');
    }

    function input_pelanggaran($id)
    {
        $data['s'] = $this->Siswa_model->get_siswa($id);
        $data['detail'] = $this->Siswa_model->detail_data($id);

        $data['pelanggaranringan'] = $this->Kategori_model->get_pelanggaran_pengasuhan_ringan();
        $data['pelanggaransedang'] = $this->Kategori_model->get_pelanggaran_pengasuhan_sedang();
        $data['pelanggaranberat'] = $this->Kategori_model->get_pelanggaran_pengasuhan_berat();
        $data['penghukumpengasuhan'] = $this->Kategori_model->get_penghukum_pengasuhan();
        $data['penghukumkeamanan'] = $this->Kategori_model->get_penghukum_keamanan();


        $this->load->view('template/header');
        $this->load->view('template/sidebar');
        $this->load->view('pelanggaran/input_pelanggaran', $data);
        $this->load->view('template/footer');
    }

    function tambah_pelanggaran(){
        
        $id_siswa =  $this->input->post('id_siswa');
        $nama_lengkap = $this->input->post('nama_lengkap');
        $nama_pelanggaran = $this->input->post('nama_pelanggaran');
        $kategori_pelanggaran = $this->input->post('kategori');
        $penghukum = $this->input->post('penghukum');
        $hukuman = $this->input->post('hukuman');
        $keterangan = $this->input->post('keterangan');


        $data = array(
            'id_siswa' => $id_siswa,
            'nama_pelanggaran' => $nama_pelanggaran,
            'nama_lengkap' => $nama_lengkap,
            'kategori_pelanggaran' => $kategori_pelanggaran,
            'nama_penghukum' => $penghukum,
            'hukuman' => $hukuman,
            'keterangan' => $keterangan,);
            

        $this->Pelanggaran_pengasuhan_model->tambah_pelanggaran($data);
        $this->session->set_flashdata('berhasil', 'Anda berhasil menambahkan data pelanggaran <strong>' . $nama_lengkap . '</strong>' . ' berupa <strong>' . $nama_pelanggaran . '</strong>' );
        redirect('pelanggaran');
    }

    function hapus_pelanggaran($id_siswa)
    {
        $id_siswa = $this->input->post('id_siswa');
        $id_pelanggaran = $this->input->post('id_pelanggaran');
        $nama_pelanggaran = $this->input->post('nama_pelanggaran');
        $hapus = $this->input->post('hapus');
        $siswa = $this->Siswa_model->get_siswa($id_siswa);
        

        if ($hapus == 1) {
            $this->session->set_flashdata('hapus', 'Anda berhasil menghapus data pelanggaran <strong>' . $siswa['nama_lengkap'] . '</strong>' . ' berupa <strong>' . $nama_pelanggaran . '</strong>' );
            $this->Pelanggaran_pengasuhan_model->delete_pelanggaran($id_pelanggaran);
            redirect(base_url('pelanggaran/detail/' . $id_siswa)) ;
        } else
            show_error('The siswa you are trying to delete does not exist.');

    }

    function print ($id)
    {
        $id_siswa = $this->input->post('id_siswa');
        $filterid = $this->input->post('print');

        if ($filterid == 1) {
            $data['title'] = "Data Santri $id";
            $data['datafilter'] =$this->Pelanggaran_pengasuhan_model->filter_by_id_siswa($id_siswa);
            $data['detail'] =$this->Siswa_model->detail_data($id_siswa);
            $data['s'] = $this->Siswa_model->get_siswa($id);

            $data['_view'] = 'pelanggaran/detail';
 
            $this->load->view('pelanggaran/print_laporan', $data);
            $this->load->view('template/footer', $data);
        }
    }
       
    function form_filter_tanggal ()
    {
        $this->load->view('template/header');
        $this->load->view('template/sidebar');
        $this->load->view('pelanggaran/form_filter_tanggal');
        $this->load->view('template/footer');
    }
   
    function filterbytanggal()
    {
        $tanggalawal = $this->input->post('tanggalawal');
        $tanggalakhir = $this->input->post('tanggalakhir');
        $nilaitanggal = $this->input->post('nilaitanggal');

           
        if ($nilaitanggal == 1) {
            $data['title'] = "Data Santri yang melanggar dari tanggal '. <?php echo format_tanggal ($tanggalawal) ?> .'  hingga '. <?php echo format_tanggal ($tanggalakhir) ?>.'";
            $data['tanggalawal'] = $tanggalawal;
            $data['tanggalakhir'] = $tanggalakhir;

           
            $data['dataghosob'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_ghosob($tanggalawal,$tanggalakhir);
            $data['datatidakpakaisendal'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_tidak_pakai_sendal($tanggalawal,$tanggalakhir);
            $data['datamenjemurpakaian'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_menjemur_pakaian_di_kamar($tanggalawal,$tanggalakhir);
            $data['datatidakmenguncilemari'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_tidak_mengunci_lemari($tanggalawal,$tanggalakhir);
            $data['datatidakmemakaiperlengkapanlengkap'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_tidak_memakai_perlengkapan_lengkap($tanggalawal,$tanggalakhir);
            $data['dataterlambat'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_terlambat($tanggalawal,$tanggalakhir);
            $data['datatidakmemakaipapannama'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_tidak_memakai_papan_nama($tanggalawal,$tanggalakhir);
            $data['datasembunyidarikegiatan'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_sembunyi_dari_kegiatan($tanggalawal,$tanggalakhir);
            $data['datakaburketikamobilisasi'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_kabur_ketika_mobilisasi($tanggalawal,$tanggalakhir);
            $data['datamokel'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_mokel($tanggalawal,$tanggalakhir);
            $data['datatidakdatangpanggilan'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_tidak_datang_panggilan_bagian_lebih_dari_3_hari($tanggalawal,$tanggalakhir);
            $data['datamelanggarnormasusila'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_melanggar_norma_susila($tanggalawal,$tanggalakhir);
            $data['datamencuri'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_mencuri($tanggalawal,$tanggalakhir);
            $data['databerkelahi'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_berkelahi($tanggalawal,$tanggalakhir);
            $data['datakaburdaripondok'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_kabur_dari_pondok($tanggalawal,$tanggalakhir);
            $data['databerhubungandenganorangkampung'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_berhubungan_dengan_orang_kampung($tanggalawal,$tanggalakhir);
            $data['datamelawanpembantupimpinanpondok'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_melawan_pembantu_pimpinan_pondok($tanggalawal,$tanggalakhir);
            $data['dataterlambatkemasjid'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_terlambat_ke_masjid($tanggalawal,$tanggalakhir);
            $data['datamenyeretsandal'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_menyeret_sandal($tanggalawal,$tanggalakhir);
            

            $data['datapelanggaranringan'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_ringan($tanggalawal,$tanggalakhir);
    
            $this->load->view('template/header', $data);
            $this->load->view('template/sidebar', $data);
            $this->load->view('pelanggaran/print_grafik', $data);
            $this->load->view('template/footer', $data);
    
        }
    }

    /*
     * Editing a kelas
     */
    function edit_pelanggaran($id)
    {   

        $data['pelanggaranringan'] = $this->Kategori_model->get_pelanggaran_pengasuhan_ringan();
        $data['pelanggaransedang'] = $this->Kategori_model->get_pelanggaran_pengasuhan_sedang();
        $data['pelanggaranberat'] = $this->Kategori_model->get_pelanggaran_pengasuhan_berat();

        // check if the pelanggaran exists before trying to edit it
        $data['pelanggaran'] = $this->Pelanggaran_pengasuhan_model->get_pelanggaran($id);

        if(isset($data['pelanggaran']['id']))
        {
            $this->load->library('form_validation');
			$this->form_validation->set_rules('penghukum','Penghukum','required');

            $id_siswa = $data['pelanggaran']['id_siswa'];
            $data['s'] = $this->Siswa_model->get_siswa($id_siswa);
            $data['detail'] = $this->Siswa_model->detail_data($id_siswa);
		
			if($this->form_validation->run())     
            {   
                $params = array(
                    'nama_penghukum' => $this->input->post('penghukum'),
                    'hukuman' => $this->input->post('hukuman'),
                    'keterangan' => $this->input->post('keterangan'),
                );

                $nama_siswa = $this->input->post('nama_lengkap');

                $this->Pelanggaran_pengasuhan_model->update_pelanggaran($id,$params);
                $this->session->set_flashdata('berhasil', 'Anda berhasil mengubah data hukuman pelanggaran <strong>' . $nama_siswa . '</strong>' . ' menjadi <strong>' . $data['pelanggaran']['hukuman'] . '</strong>');

                redirect(base_url('pelanggaran/detail/' . $id_siswa)) ;
            }
            else
            {
                $data['penghukumpengasuhan'] = $this->Kategori_model->get_penghukum_pengasuhan();
                $data['penghukumkeamanan'] = $this->Kategori_model->get_penghukum_keamanan();

                $data['_view'] = 'pelanggaran/edit_pelanggaran';
                $this->load->view('template/header',$data);
                $this->load->view('template/sidebar',$data);
                $this->load->view('pelanggaran/edit_pelanggaran',$data);
                $this->load->view('template/footer',$data);
            }
        }
        else
            show_error('The Siswa you are trying to edit does not exist.');
    } 
   
    function fill_kategori_pelanggaran(){
        $nama_pelanggaran = $_POST['nama_pelanggaran'];
        $s = "SELECT kategori as kategori FROM tb_pelanggaran_pengasuhan WHERE nama_pelanggaran='$nama_pelanggaran'";

        $res = $this->db->query($s)->row_array();
        echo json_encode($res);
    }

     /*
     * Fungsi Input Massal
     */
    function input_massal()
    {   
        $data['siswa'] = $this->Siswa_model->get_aktif_siswa();

        $data['pelanggaranringan'] = $this->Kategori_model->get_pelanggaran_pengasuhan_ringan();
        $data['pelanggaransedang'] = $this->Kategori_model->get_pelanggaran_pengasuhan_sedang();
        $data['pelanggaranberat'] = $this->Kategori_model->get_pelanggaran_pengasuhan_berat();
        $data['penghukumpengasuhan'] = $this->Kategori_model->get_penghukum_pengasuhan();
        $data['penghukumkeamanan'] = $this->Kategori_model->get_penghukum_keamanan();

        $this->load->library('form_validation');

		$this->form_validation->set_rules('nama_pelanggaran','Pelanggaran','required');
		
		if($this->form_validation->run())     
        {   
            $params = array();
            $id_siswa = $this->input->post('id_siswa[]');
            $nama_lengkap = $this->input->post('nama_lengkap[]');
            $nama_pelanggaran = $this->input->post('nama_pelanggaran');
            $kategori_pelanggaran = $this->input->post('kategori');
            $penghukum = $this->input->post('penghukum');
            $hukuman = $this->input->post('hukuman');
            $keterangan = $this->input->post('keterangan');

            foreach($id_siswa as $siswa){
                array_push($params, [
                    'nama_lengkap' => $nama_lengkap,
                    'nama_pelanggaran' => $nama_pelanggaran,
                    'kategori_pelanggaran' => $kategori_pelanggaran,
                    'nama_penghukum' => $penghukum,
                    'hukuman' => $hukuman,
                    'keterangan' => $keterangan,
                    'id_siswa' => $siswa
                ]);
            }

            print_r($params);
            
            // $this->Rombel_model->add_rombel($params);
            // $this->session->set_flashdata('berhasil', 'Anda berhasil menambahkan data id kelas <strong>'.$params['id_kelas'].'</strong>');
            // redirect('rombel/index');
        }
        else
        {
		
            $data['_view'] = 'rombel/add';
            $this->load->view('template/header',$data);
            $this->load->view('template/sidebar',$data);
            $this->load->view('pelanggaran/input_massal',$data);
            $this->load->view('template/footer',$data);
        }
    }  

    function simpan_massal()
    {
        $result = $this->input->post('id_siswa[]');

        $params = array();
        $nama_pelanggaran = $this->input->post('nama_pelanggaran');
        $kategori_pelanggaran = $this->input->post('kategori');
        $penghukum = $this->input->post('penghukum');
        $hukuman = $this->input->post('hukuman');
        $keterangan = $this->input->post('keterangan');

        foreach($result as $result){
            $result_explode = explode('|', $result);

            $id_siswa = $result_explode[0];
            $nama_lengkap = $result_explode[1];

            array_push($params, [
                'nama_lengkap' => $nama_lengkap,
                'nama_pelanggaran' => $nama_pelanggaran,
                'kategori_pelanggaran' => $kategori_pelanggaran,
                'nama_penghukum' => $penghukum,
                'hukuman' => $hukuman,
                'keterangan' => $keterangan,
                'id_siswa' => $id_siswa
            ]);

        $this->session->set_flashdata('berhasil', 'Anda berhasil menambahkan data pelanggaran <strong>'.$nama_pelanggaran.'</strong>');
        }

        $this->db->insert_batch('record_pelanggaran_pengasuhan', $params);
        redirect('pelanggaran');
    }

}
