<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Helper\Sample;

class Rekap_kelas extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Siswa_model');

        // cek user login
        check_login();
    }

    /*
     * Listing of Rekap Siswa
     */
    function index()
    {
        $data['_view'] = 'rekap_kelas/index';

        $this->load->view('template/header', $data);
        $this->load->view('template/sidebar', $data);
        $this->load->view('rekap_kelas/index', $data);
        $this->load->view('template/footer', $data);
    }

    /*
     * Listing of Rekap Siswa
     */
    function print()
    {
        $data['_view'] = 'rekap_kelas/index';

        // $this->load->view('template/header', $data);
        // $this->load->view('template/sidebar', $data);
        $this->load->view('rekap_kelas/print_laporan', $data);
        $this->load->view('template/footer', $data);
    }

}
