<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

 use PhpOffice\PhpSpreadsheet\Helper\Sample;
 use PhpOffice\PhpSpreadsheet\IOFactory;
 use PhpOffice\PhpSpreadsheet\Spreadsheet;
 use PhpOffice\PhpSpreadsheet\Style\Protection;

class Siswa extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Siswa_model');
        $this->load->model('Kategori_model');

        // cek user login
        check_login();
    }

    /*
     * FUNGSI UNTUK MUNCULKAN DATA SANTRI
     */
    function index()
    {
        $data['siswa'] = $this->Siswa_model->get_aktif_siswa();

        $data['_view'] = 'siswa/index';

        $this->load->view('template/header', $data);
        $this->load->view('template/sidebar', $data);
        $this->load->view('siswa/index', $data);
        $this->load->view('template/footer', $data);
    }

    /*
     * FUNGSI UNTUK TAMBAH DATA SANTRI
     */
    function add()
    {
        $this->load->helper('string');
        $this->load->library('form_validation');

        $this->form_validation->set_rules('nama_lengkap', 'Nama Lengkap' ,'required');
        $this->form_validation->set_rules('nis', 'Nomor Induk Siswa', 'required');

        if ($this->form_validation->run()) {
            
            // upload data
            $params = array(
                'nis' => $this->input->post('nis'),
                'tahun_masuk' => $this->input->post('tahun_masuk'),
                'nama_lengkap' => $this->input->post('nama_lengkap'),
                'nama_arab' => $this->input->post('nama_arab'),
                'nama_panggilan' => $this->input->post('nama_panggilan'),
                'nisn' => $this->input->post('nisn'),
                'kelas' => $this->input->post('kelas'),
                'konsul' => $this->input->post('konsul'),
                'nik' => $this->input->post('nik'),
                'no_kis' => $this->input->post('no_kis'),
                'tempat_lahir' => $this->input->post('tempat_lahir'),
                'tanggal_lahir' => $this->input->post('tanggal_lahir'),
                'kewarganegaraan' => $this->input->post('kewarganegaraan'),
                'suku' => $this->input->post('suku'),
                'alamat' => $this->input->post('alamat'),
                'kelurahan' => ($this->input->post('kelurahan') === '' )? NULL : $this->input->post('kelurahan'),
                'kecamatan' => ($this->input->post('kecamatan') === '' )? NULL : $this->input->post('kecamatan'),
                'kota_kab' => ($this->input->post('kota_kab') === '' )? NULL : $this->input->post('kota_kab'),
                'provinsi' => ($this->input->post('provinsi') === '' )? NULL : $this->input->post('provinsi'),
                'kode_pos' => ($this->input->post('kode_pos') === '' )? NULL : $this->input->post('kode_pos'),
                'rayon' => $this->input->post('rayon'),
                'aktif' => $this->input->post('aktif'),
                'no_telp' => $this->input->post('no_telp'),
                'facebook' => $this->input->post('facebook'),
                'twitter' => $this->input->post('twitter'),
                'email' => $this->input->post('email'),
                'dibesarkan_di' => $this->input->post('dibesarkan_di'),
                'ayah' => $this->input->post('ayah'),
                'usia_ayah' => $this->input->post('usia_ayah'),
                'pekerjaan_ayah' => $this->input->post('pekerjaan_ayah'),
                'agama_ayah' => $this->input->post('agama_ayah'),
                'pend_ayah' => $this->input->post('pend_ayah'),
                'kewarga_ayah' => $this->input->post('kewarga_ayah'),
                'suku_ayah' => $this->input->post('suku_ayah'),
                'ormas_ayah' => $this->input->post('ormas_ayah'),
                'orpol_ayah' => $this->input->post('orpol_ayah'),
                'kedudukan_ayah' => $this->input->post('kedudukan_ayah'),
                'alumni_ayah' => $this->input->post('alumni_ayah'),
                'stambuk_ayah' => $this->input->post('stambuk_ayah'),
                'tahun_lulus_ayah' => $this->input->post('tahun_lulus_ayah'),
                'telp_ayah' => $this->input->post('telp_ayah'),
                'ibu' => $this->input->post('ibu'),
                'usia_ibu' => $this->input->post('usia_ibu'),
                'pekerjaan_ibu' => $this->input->post('pekerjaan_ibu'),
                'pend_ibu' => $this->input->post('pend_ibu'),
                'agama_ibu' => $this->input->post('agama_ibu'),
                'kewarga_ibu' => $this->input->post('kewarga_ibu'),
                'suku_ibu' => $this->input->post('suku_ibu'),
                'ormas_ibu' => $this->input->post('ormas_ibu'),
                'orpal_ibu' => $this->input->post('orpal_ibu'),
                'kedudukan_ibu' => $this->input->post('kedudukan_ibu'),
                'alumni_ibu' => $this->input->post('alumni_ibu'),
                'stambuk_ibu' => $this->input->post('stambuk_ibu'),
                'tahun_lulus_ibu' => $this->input->post('tahun_lulus_ibu'),
                'telp_ibu' => $this->input->post('telp_ibu'),
                'yang_membiayai' => $this->input->post('yang_membiayai'),
                'minimal_membiayai' => $this->input->post('minimal_membiayai'),
                'maksimal_membiayai' => $this->input->post('maksimal_membiayai'),
                'wali' => $this->input->post('wali'),
                'usia_wali' => $this->input->post('usia_wali'),
                'hubungan_wali' => $this->input->post('hubungan_wali'),
                'pekerjaan_wali' => $this->input->post('pekerjaan_wali'),
                'pend_wali' => $this->input->post('pend_wali'),
                'agama_wali' => $this->input->post('agama_wali'),
                'kewarga_wali' => $this->input->post('kewarga_wali'),
                'suku_wali' => $this->input->post('suku_wali'),
                'ormas_wali' => $this->input->post('ormas_wali'),
                'orpol_wali' => $this->input->post('orpol_wali'),
                'kedudukan_wali' => $this->input->post('kedudukan_wali'),
                'alumni_wali' => $this->input->post('alumni_wali'),
                'stambuk_wali' => $this->input->post('stambuk_wali'),
                'tahun_lulus_wali' => $this->input->post('tahun_lulus_wali'),
                'telp_wali' => $this->input->post('telp_wali'),
                'gol_darah' => $this->input->post('gol_darah'),
                'tinggi_badan' => $this->input->post('tinggi_badan'),
                'berat_badan' => $this->input->post('berat_badan'),
                'khitan' => $this->input->post('khitan'),
                'kondisi_rumah' => $this->input->post('kondisi_rumah'),
                'situasi_kehidupan_beragama' => $this->input->post('situasi_kehidupan_beragama'),
                'kondisi_ekonomi' => $this->input->post('kondisi_ekonomi'),
                'situasi_rumah' => $this->input->post('situasi_rumah'),
                'letak_rumah' => $this->input->post('letak_rumah'),
                'penglihatan_mata' => $this->input->post('penglihatan_mata'),
                'pakai_kacamata' => $this->input->post('pakai_kacamata'),
                'kacamata_tahun' => $this->input->post('kacamata_tahun'),
                'pendengaran_telinga' => $this->input->post('pendengaran_telinga'),
                'operasi' => $this->input->post('operasi'),
                'kecelakaan' => $this->input->post('kecelakaan'),
                'alergi' => $this->input->post('alergi'),
                'alergi_dari_tahun' => $this->input->post('alergi_dari_tahun'),
                'jenis_alergi' => $this->input->post('jenis_alergi'),
                'kelainan_fisik' => $this->input->post('kelainan_fisik'),
                'sakit_tahun' => $this->input->post('sakit_tahun'),
                'sakit_nama' => $this->input->post('sakit_nama'),
                'sakit_kriteria' => $this->input->post('sakit_kriteria'),
                'sakit_menular' => $this->input->post('sakit_menular'),
                'sakit_keterangan' => $this->input->post('sakit_keterangan'),
                'bidang_studi' => $this->input->post('bidang_studi'),
                'olah_raga' => $this->input->post('olah_raga'),
                'kesenian' => $this->input->post('kesenian'),
                'keterampilan' => $this->input->post('keterampilan'),
                'lain_lain' => $this->input->post('lain_lain'),
                'klub_olah_raga' => $this->input->post('klub_olah_raga'),
                'kursus_bahasa' => $this->input->post('kursus_bahasa'),
                'kursus_kesenian' => $this->input->post('kursus_kesenian'),
                'ketermpilan_extra' => $this->input->post('ketermpilan_extra'),
                'asisten_bagian' => $this->input->post('asisten_bagian'),

            );

            $this->Siswa_model->add_siswa($params);
            $this->session->set_flashdata('berhasil', 'Anda berhasil menambahkan data <strong>' . $params['nama_lengkap'] . '</strong>');
            redirect('siswa/index');
        } else {

            $data['rayon'] = $this->Kategori_model->get_rayon();
            $data['provinsi'] = $this->Kategori_model->get_provinsi();
            $data['kabupaten'] = $this->Kategori_model->get_kabupaten();
            $data['kelas'] = $this->Kategori_model->get_kelas();

            //load view
            $data['_view'] = 'siswa/add';
            $this->load->view('template/header', $data);
            $this->load->view('template/sidebar', $data);
            $this->load->view('siswa/add', $data);
            $this->load->view('template/footer', $data);
        }
    }

    /*
     * FUNGSI UNTUK EDIT DATA SANTRI BERDASARKAN STAMBUK
     */
    function edit($nis)
    {
        // check if the siswa exists before trying to edit it
        $data['siswa'] = $this->Siswa_model->get_siswa_nis($nis);

        if (isset($data['siswa']['nis'])) {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('nama_lengkap', 'Nama Lengkap', 'required');
            $this->form_validation->set_rules('nis', 'Nomor Induk Siswa', 'required');

            if ($this->form_validation->run()) {
              
                // upload data
                $params = array(
                'nis' => $this->input->post('nis'),
                'tahun_masuk' => $this->input->post('tahun_masuk'),
                'nama_lengkap' => $this->input->post('nama_lengkap'),
                'nama_arab' => $this->input->post('nama_arab'),
                'nama_panggilan' => $this->input->post('nama_panggilan'),
                'nisn' => $this->input->post('nisn'),
                'kelas' => $this->input->post('kelas'),
                'konsul' => $this->input->post('konsul'),
                'nik' => $this->input->post('nik'),
                'no_kis' => $this->input->post('no_kis'),
                'tempat_lahir' => $this->input->post('tempat_lahir'),
                'tanggal_lahir' => $this->input->post('tanggal_lahir'),
                'kewarganegaraan' => $this->input->post('kewarganegaraan'),
                'suku' => $this->input->post('suku'),
                'alamat' => $this->input->post('alamat'),
                'kelurahan' => ($this->input->post('kelurahan') === '' )? NULL : $this->input->post('kelurahan'),
                'kecamatan' => ($this->input->post('kecamatan') === '' )? NULL : $this->input->post('kecamatan'),
                'kota_kab' => ($this->input->post('kota_kab') === '' )? NULL : $this->input->post('kota_kab'),
                'provinsi' => ($this->input->post('provinsi') === '' )? NULL : $this->input->post('provinsi'),
                'kode_pos' => ($this->input->post('kode_pos') === '' )? NULL : $this->input->post('kode_pos'),
                'rayon' => $this->input->post('rayon'),
                'aktif' => $this->input->post('aktif'),
                'no_telp' => $this->input->post('no_telp'),
                'facebook' => $this->input->post('facebook'),
                'twitter' => $this->input->post('twitter'),
                'email' => $this->input->post('email'),
                'dibesarkan_di' => $this->input->post('dibesarkan_di'),
                'ayah' => $this->input->post('ayah'),
                'usia_ayah' => $this->input->post('usia_ayah'),
                'pekerjaan_ayah' => $this->input->post('pekerjaan_ayah'),
                'agama_ayah' => $this->input->post('agama_ayah'),
                'pend_ayah' => $this->input->post('pend_ayah'),
                'kewarga_ayah' => $this->input->post('kewarga_ayah'),
                'suku_ayah' => $this->input->post('suku_ayah'),
                'ormas_ayah' => $this->input->post('ormas_ayah'),
                'orpol_ayah' => $this->input->post('orpol_ayah'),
                'kedudukan_ayah' => $this->input->post('kedudukan_ayah'),
                'alumni_ayah' => $this->input->post('alumni_ayah'),
                'stambuk_ayah' => $this->input->post('stambuk_ayah'),
                'tahun_lulus_ayah' => $this->input->post('tahun_lulus_ayah'),
                'telp_ayah' => $this->input->post('telp_ayah'),
                'ibu' => $this->input->post('ibu'),
                'usia_ibu' => $this->input->post('usia_ibu'),
                'pekerjaan_ibu' => $this->input->post('pekerjaan_ibu'),
                'pend_ibu' => $this->input->post('pend_ibu'),
                'agama_ibu' => $this->input->post('agama_ibu'),
                'kewarga_ibu' => $this->input->post('kewarga_ibu'),
                'suku_ibu' => $this->input->post('suku_ibu'),
                'ormas_ibu' => $this->input->post('ormas_ibu'),
                'orpal_ibu' => $this->input->post('orpal_ibu'),
                'kedudukan_ibu' => $this->input->post('kedudukan_ibu'),
                'alumni_ibu' => $this->input->post('alumni_ibu'),
                'stambuk_ibu' => $this->input->post('stambuk_ibu'),
                'tahun_lulus_ibu' => $this->input->post('tahun_lulus_ibu'),
                'telp_ibu' => $this->input->post('telp_ibu'),
                'yang_membiayai' => $this->input->post('yang_membiayai'),
                'minimal_membiayai' => $this->input->post('minimal_membiayai'),
                'maksimal_membiayai' => $this->input->post('maksimal_membiayai'),
                'wali' => $this->input->post('wali'),
                'usia_wali' => $this->input->post('usia_wali'),
                'hubungan_wali' => $this->input->post('hubungan_wali'),
                'pekerjaan_wali' => $this->input->post('pekerjaan_wali'),
                'pend_wali' => $this->input->post('pend_wali'),
                'agama_wali' => $this->input->post('agama_wali'),
                'kewarga_wali' => $this->input->post('kewarga_wali'),
                'suku_wali' => $this->input->post('suku_wali'),
                'ormas_wali' => $this->input->post('ormas_wali'),
                'orpol_wali' => $this->input->post('orpol_wali'),
                'kedudukan_wali' => $this->input->post('kedudukan_wali'),
                'alumni_wali' => $this->input->post('alumni_wali'),
                'stambuk_wali' => $this->input->post('stambuk_wali'),
                'tahun_lulus_wali' => $this->input->post('tahun_lulus_wali'),
                'telp_wali' => $this->input->post('telp_wali'),
                'gol_darah' => $this->input->post('gol_darah'),
                'tinggi_badan' => $this->input->post('tinggi_badan'),
                'berat_badan' => $this->input->post('berat_badan'),
                'khitan' => $this->input->post('khitan'),
                'kondisi_rumah' => $this->input->post('kondisi_rumah'),
                'situasi_kehidupan_beragama' => $this->input->post('situasi_kehidupan_beragama'),
                'kondisi_ekonomi' => $this->input->post('kondisi_ekonomi'),
                'situasi_rumah' => $this->input->post('situasi_rumah'),
                'letak_rumah' => $this->input->post('letak_rumah'),
                'penglihatan_mata' => $this->input->post('penglihatan_mata'),
                'pakai_kacamata' => $this->input->post('pakai_kacamata'),
                'kacamata_tahun' => $this->input->post('kacamata_tahun'),
                'pendengaran_telinga' => $this->input->post('pendengaran_telinga'),
                'operasi' => $this->input->post('operasi'),
                'sebab_operasi' => $this->input->post('sebab_operasi'),
                'kecelakaan' => $this->input->post('kecelakaan'),
                'alergi' => $this->input->post('alergi'),
                'alergi_dari_tahun' => $this->input->post('alergi_dari_tahun'),
                'jenis_alergi' => $this->input->post('jenis_alergi'),
                'kelainan_fisik' => $this->input->post('kelainan_fisik'),
                'sakit_tahun' => $this->input->post('sakit_tahun'),
                'sakit_nama' => $this->input->post('sakit_nama'),
                'sakit_kriteria' => $this->input->post('sakit_kriteria'),
                'sakit_menular' => $this->input->post('sakit_menular'),
                'sakit_keterangan' => $this->input->post('sakit_keterangan'),
                'bidang_studi' => $this->input->post('bidang_studi'),
                'olah_raga' => $this->input->post('olah_raga'),
                'kesenian' => $this->input->post('kesenian'),
                'keterampilan' => $this->input->post('keterampilan'),
                'lain_lain' => $this->input->post('lain_lain'),
                'klub_olah_raga' => $this->input->post('klub_olah_raga'),
                'kursus_bahasa' => $this->input->post('kursus_bahasa'),
                'kursus_kesenian' => $this->input->post('kursus_kesenian'),
                'ketermpilan_extra' => $this->input->post('ketermpilan_extra'),
                'asisten_bagian' => $this->input->post('asisten_bagian'),
                
                );

                $this->Siswa_model->update_siswa($nis, $params);
                
                $this->session->set_flashdata('berhasil', 'Anda berhasil mengubah data <strong>' . $params['nama_lengkap'] . '</strong>');
                redirect('siswa/index');
            } else {

                $data['saudara_siswa'] = $this->Siswa_model->get_saudara_siswa_bystambuk($data['siswa']['nis']);
                $data['rayon'] = $this->Kategori_model->get_rayon();
                $data['provinsi'] = $this->Kategori_model->get_provinsi();
                $data['kabupaten'] = $this->Kategori_model->get_kabupaten();
                $data['kelas'] = $this->Kategori_model->get_kelas();

                // upload view
                $data['_view'] = 'siswa/edit';
                $this->load->view('template/header', $data);
                $this->load->view('template/sidebar', $data);
                $this->load->view('siswa/edit', $data);
                $this->load->view('template/footer', $data);
            }
        } else
            show_error('The siswa you are trying to edit does not exist.');
    }

    /*
     * FUNGSI UNTUK HAPUS DATA SANTRI
     */
    function remove($id)
    {
        $siswa = $this->Siswa_model->get_siswa($id);
        // check if the siswa exists before trying to delete it
        if (isset($siswa['id'])) {
            $this->Siswa_model->delete_siswa($id);
            $this->session->set_flashdata('hapus', 'Anda berhasil menghapus data <strong>' . $siswa['nama_lengkap'] . '</strong>');
            redirect('siswa/index');
        } else
            show_error('The siswa you are trying to delete does not exist.');
    }

    /*
    * FUNGSI UNTUK UPLOAD MASSAL DATA SANTRI
    */
    function do_upload()
    {
        $file_ext = pathinfo($_FILES["userfile"]["name"], PATHINFO_EXTENSION);

        $config['upload_path']          = './uploads/';
        $config['allowed_types']        = 'xlsx|xls|csv';
        $config['overwrite']             = true;
        $config['file_name']             = 'siswa';

        $this->load->library('upload', $config);

        if (!$this->upload->do_upload('userfile')) {
            $error = array('error' => $this->upload->display_errors());
            print_r($error);
        } else {
            $data = array('upload_data' => $this->upload->data());

            $helper = new Sample();
            $inputFileName = 'uploads/'.$data['upload_data']['file_name'];
            $helper->log('Loading file ' . pathinfo($inputFileName, PATHINFO_BASENAME) . ' using IOFactory to identify the format');
            $spreadsheet = IOFactory::load($inputFileName);
            $sheetData = $spreadsheet->getActiveSheet()->toArray(null, true, true, true);
            $highestRow = $spreadsheet->getActiveSheet()->getHighestRow();

            // hitung jumlah data yang di upload
            $jumlahData = $highestRow - 1;
            $dataAwal = array();
            foreach ($sheetData as $s) {
                array_push($dataAwal, array(
                    'kelas' => $s['D'],
                    'konsul' => $s['E'],
                    'kewarganegaraan' => $s['U'],
                    'suku' => $s['V'],
                    'nama_lengkap' => $s['C'],
                    'nama_arab' => $s['H'],
                    'nama_panggilan' => $s['I'],
                    'nis' => $s['J'],
                    'tahun_masuk' => $s['K'],
                    'nik' => $s['L'],
                    'no_kis' => $s['M'],
                    'tempat_lahir' => $s['N'],
                    'tanggal_lahir' => $s['O'],
                    'alamat' => $s['G'],
                    'kelurahan' => $s['P'],
                    'kecamatan' => $s['Q'],
                    'kota_kab' => $s['R'],
                    'provinsi' => $s['S'],
                    'kode_pos' => $s['T'],  
                    'ayah' => $s['W'],
                    'pekerjaan_ayah' => $s['X'],
                    'pend_ayah' => $s['Y'],
                    'agama_ayah' => $s['Z'],
                    'kewarga_ayah' => $s['AA'],
                    'suku_ayah' => $s['AB'],
                    'ormas_ayah' => $s['AC'],
                    'orpol_ayah' => $s['AD'],
                    'kedudukan_ayah' => $s['AE'],
                    'alumni_ayah' => $s['AF'],
                    'ibu' => $s['AG'],
                    'pekerjaan_ibu' => $s['AH'],
                    'pend_ibu' => $s['AI'],
                    'agama_ibu' => $s['AJ'],
                    'kewarga_ibu' => $s['AK'],
                    'suku_ibu' => $s['AL'],
                    'ormas_ibu' => $s['AM'],
                    'orpal_ibu' => $s['AN'],
                    'kedudukan_ibu' => $s['AO'],
                    'alumni_ibu' => $s['AP'],
                    'wali' => $s['AQ'],
                    'hubungan_wali' => $s['AR'],
                    'pekerjaan_wali' => $s['AS'],
                    'pend_wali' => $s['AT'],
                    'agama_wali' => $s['AU'],
                    'kewarga_wali' => $s['AV'],
                    'suku_wali' => $s['AW'],
                    'ormas_wali' => $s['AX'],
                    'orpol_wali' => $s['AY'],
                    'kedudukan_wali' => $s['AZ'],
                    'alumni_wali' => $s['BA'],
                    'rayon' => $s['F'],
                    'telp_wali' => $s['BB'],
                    'telp_ayah' => $s['BC'],
                    'telp_ibu' => $s['BD'],
                    'gol_darah' => $s['BE'],
                    'tinggi_badan' => $s['BF'],
                    'berat_badan' => $s['BG'],
                    'kondisi_rumah' => $s['BH'],
                    'kondisi_ekonomi' => $s['BI'],
                    'situasi_rumah' => $s['BJ'],
                    'letak_rumah' => $s['BK'],
                    'penglihatan_mata' => $s['BL'],
                    'pakai_kacamata' => $s['BM'],
                    'pendengaran_telinga' => $s['BN'],
                    'operasi' => $s['BO'],
                    'kecelakaan' => $s['BP'],
                    'alergi' => $s['BQ'],
                    'kelainan_fisik' => $s['BR'],
                    'sakit_tahun' => $s['BS'],
                    'sakit_nama' => $s['BT'],
                    'sakit_kriteria' => $s['BU'],
                    'sakit_menular' => $s['BV'],
                    'sakit_keterangan' => $s['BW'],
                    'bidang_studi' => $s['BX'],
                    'olah_raga' => $s['BY'],
                    'kesenian' => $s['BZ'],
                    'keterampilan' => $s['CA'],
                    'lain_lain' => $s['CB'],
                    'klub_olah_raga' => $s['CC'],
                    'kursus_bahasa' => $s['CD'],
                    'kursus_kesenian' => $s['CF'],
                    'ketermpilan_extra' => $s['CF'],
                    'asisten_bagian' => $s['CG'],
                    
                    'foto' => NULL,
                    'aktif' => '1' // aktif
                ));
            }
            // $dataAwal membaca semua data yang ada di excel termasuk nama kolom
            // $dataAkhir membaca $dataAwal dari array urutan ke 2
            $dataAkhir = array_slice($dataAwal, 1);
            $this->session->set_flashdata('berhasil_upload', 'Anda berhasil mengunggah <strong>' . $jumlahData . ' data siswa.</strong>');
            $this->db->insert_batch('siswa', $dataAkhir);
            unlink($inputFileName);
            redirect('siswa');
        }
    }

    // FUNGSI UNTUK DOWNLOAD TEMPLATE UPDATE DATA SANTRI
    function download_template_siswa()
    {
        force_download('downloads/template_siswa.xlsx', null);
    }

    // FUNGSI UNTUK HAPUS SEMUA DATA SANTRI
    function delete_all_siswa()
    {
        $this->db->empty_table('siswa'); // Produces: DELETE FROM siswa
        redirect('siswa');
    }

    /*
    * FUNGSI UNTUK DOWNLOAD DATA SANTRI
    */
    function download()
    {
        // dapatkan semua siswa dalam rombel berdasarkan id kelas yang aktif
        $data['siswa'] = $this->Siswa_model->tampil_data('sim_pondok')->result();

        // Create new Spreadsheet object
        $spreadsheet = new Spreadsheet();

        // Set document properties
        $spreadsheet->getProperties()->setCreator('Pusat Data Gontor 2')
            ->setLastModifiedBy('Pusat Data Gontor 2')
            ->setTitle('Office 2007 XLSX Download Data Santri')
            ->setSubject('Office 2007 XLSX Download Data Santri')
            ->setDescription('Download Data Santri for Office 2007 XLSX, generated using PHP classes.')
            ->setKeywords('office 2007 openxml php')
            ->setCategory('Siakad Excel');

        // Rename worksheet
        $spreadsheet->getActiveSheet()->setTitle('Master Data Santri');

        // Set active sheet index to the first sheet, so Excel opens this as the first sheet
        $spreadsheet->setActiveSheetIndex(0);

        // masukkan judul
        $spreadsheet->getActiveSheet()->setCellValue('A1', 'No');
        $spreadsheet->getActiveSheet()->setCellValue('B1', 'Stambuk');
        $spreadsheet->getActiveSheet()->setCellValue('C1', 'Nama Lengkap');
        $spreadsheet->getActiveSheet()->setCellValue('D1', 'Kelas');
        $spreadsheet->getActiveSheet()->setCellValue('E1', 'Konsulat');
        $spreadsheet->getActiveSheet()->setCellValue('F1', 'Rayon');
        $spreadsheet->getActiveSheet()->setCellValue('G1', 'Alamat');
        $spreadsheet->getActiveSheet()->setCellValue('H1', 'Nama Arab');
        $spreadsheet->getActiveSheet()->setCellValue('I1', 'Nama Panggilan');
        $spreadsheet->getActiveSheet()->setCellValue('J1', 'NISN');
        $spreadsheet->getActiveSheet()->setCellValue('K1', 'Tahun Masuk');
        $spreadsheet->getActiveSheet()->setCellValue('L1', 'NIK');
        $spreadsheet->getActiveSheet()->setCellValue('M1', 'No KIS');
        $spreadsheet->getActiveSheet()->setCellValue('N1', 'Tempat Lahir');
        $spreadsheet->getActiveSheet()->setCellValue('O1', 'Tanggal Lahir');
        $spreadsheet->getActiveSheet()->setCellValue('P1', 'Kelurahan');
        $spreadsheet->getActiveSheet()->setCellValue('Q1', 'Kecamatan');
        $spreadsheet->getActiveSheet()->setCellValue('R1', 'Kota/Kabupaten');
        $spreadsheet->getActiveSheet()->setCellValue('S1', 'Provinsi');
        $spreadsheet->getActiveSheet()->setCellValue('T1', 'Kode Pos');
        $spreadsheet->getActiveSheet()->setCellValue('U1', 'Kewarganegaraan');
        $spreadsheet->getActiveSheet()->setCellValue('V1', 'Suku');
        $spreadsheet->getActiveSheet()->setCellValue('W1', 'Ayah');
        $spreadsheet->getActiveSheet()->setCellValue('X1', 'Pekerjaan Ayah');
        $spreadsheet->getActiveSheet()->setCellValue('Y1', 'Pendidikan Terakhir Ayah');
        $spreadsheet->getActiveSheet()->setCellValue('Z1', 'Agama Ayah');
        $spreadsheet->getActiveSheet()->setCellValue('AA1', 'Kewarganegaraan Ayah');
        $spreadsheet->getActiveSheet()->setCellValue('AB1', 'Suku Ayah');
        $spreadsheet->getActiveSheet()->setCellValue('AC1', 'Ormas Ayah');
        $spreadsheet->getActiveSheet()->setCellValue('AD1', 'Orpol Ayah');
        $spreadsheet->getActiveSheet()->setCellValue('AE1', 'Kedudukan Ayah');
        $spreadsheet->getActiveSheet()->setCellValue('AF1', 'Alumni Ayah');
        $spreadsheet->getActiveSheet()->setCellValue('AG1', 'Ibu');
        $spreadsheet->getActiveSheet()->setCellValue('AH1', 'Pekerjaan Ibu');
        $spreadsheet->getActiveSheet()->setCellValue('AI1', 'Pendidikan Terakhir Ibu');
        $spreadsheet->getActiveSheet()->setCellValue('AJ1', 'Agama Ibu');
        $spreadsheet->getActiveSheet()->setCellValue('AK1', 'Kewarganegaraan Ibu');
        $spreadsheet->getActiveSheet()->setCellValue('AL1', 'Suku Ibu');
        $spreadsheet->getActiveSheet()->setCellValue('AM1', 'Ormas Ibu');
        $spreadsheet->getActiveSheet()->setCellValue('AN1', 'Orpal Ibu');
        $spreadsheet->getActiveSheet()->setCellValue('AO1', 'Kedudukan Ibu');
        $spreadsheet->getActiveSheet()->setCellValue('AP1', 'Alumni Ibu');
        $spreadsheet->getActiveSheet()->setCellValue('AQ1', 'Wali');
        $spreadsheet->getActiveSheet()->setCellValue('AR1', 'Hubungan Wali');
        $spreadsheet->getActiveSheet()->setCellValue('AS1', 'Pekerjaan Wali');
        $spreadsheet->getActiveSheet()->setCellValue('AT1', 'Pendidikan terakhir Wali');
        $spreadsheet->getActiveSheet()->setCellValue('AU1', 'Agama Wali');
        $spreadsheet->getActiveSheet()->setCellValue('AV1', 'Kewarganegaraan Wali');
        $spreadsheet->getActiveSheet()->setCellValue('AW1', 'Suku Wali');
        $spreadsheet->getActiveSheet()->setCellValue('AX1', 'Ormas Wali');
        $spreadsheet->getActiveSheet()->setCellValue('AY1', 'Orpal Wali');
        $spreadsheet->getActiveSheet()->setCellValue('AZ1', 'Kedudukan Wali');
        $spreadsheet->getActiveSheet()->setCellValue('BA1', 'Alumni Wali');
        $spreadsheet->getActiveSheet()->setCellValue('BB1', 'No Telpon Wali');
        $spreadsheet->getActiveSheet()->setCellValue('BC1', 'No Telpon Ayah');
        $spreadsheet->getActiveSheet()->setCellValue('BD1', 'No Telpon Ibu');
        $spreadsheet->getActiveSheet()->setCellValue('BE1', 'Golongan Darah');
        $spreadsheet->getActiveSheet()->setCellValue('BF1', 'Tinggi Badan');
        $spreadsheet->getActiveSheet()->setCellValue('BG1', 'Berat Badan');
        $spreadsheet->getActiveSheet()->setCellValue('BH1', 'Kondisi Rumah');
        $spreadsheet->getActiveSheet()->setCellValue('BI1', 'Kondisi Ekonomi');
        $spreadsheet->getActiveSheet()->setCellValue('BJ1', 'Situasi Rumah');
        $spreadsheet->getActiveSheet()->setCellValue('BK1', 'Letak Rumah');
        $spreadsheet->getActiveSheet()->setCellValue('BL1', 'Pengelihatan Mata');
        $spreadsheet->getActiveSheet()->setCellValue('BM1', 'Pakai Kacamata');
        $spreadsheet->getActiveSheet()->setCellValue('BN1', 'Pendengaran Telinga');
        $spreadsheet->getActiveSheet()->setCellValue('BO1', 'Operasi');
        $spreadsheet->getActiveSheet()->setCellValue('BP1', 'Kecelakaan');
        $spreadsheet->getActiveSheet()->setCellValue('BQ1', 'Alergi');
        $spreadsheet->getActiveSheet()->setCellValue('BR1', 'Kelainan Fisik');
        $spreadsheet->getActiveSheet()->setCellValue('BS1', 'Nama Penyakit');
        $spreadsheet->getActiveSheet()->setCellValue('BT1', 'Sakit Tahun');
        $spreadsheet->getActiveSheet()->setCellValue('BU1', 'Kriteria Penyakit');
        $spreadsheet->getActiveSheet()->setCellValue('BV1', 'Sakit Menular');
        $spreadsheet->getActiveSheet()->setCellValue('BW1', 'Keterangan Sakit');
        $spreadsheet->getActiveSheet()->setCellValue('BX1', 'Bidang Studi');
        $spreadsheet->getActiveSheet()->setCellValue('BY1', 'Olahraga');
        $spreadsheet->getActiveSheet()->setCellValue('BZ1', 'Kesenian');
        $spreadsheet->getActiveSheet()->setCellValue('CA1', 'Keterampilan');
        $spreadsheet->getActiveSheet()->setCellValue('CB1', 'Lain-Lain');
        $spreadsheet->getActiveSheet()->setCellValue('CC1', 'Klub Olahraga');
        $spreadsheet->getActiveSheet()->setCellValue('CD1', 'Kursus Bahasa');
        $spreadsheet->getActiveSheet()->setCellValue('CE1', 'Kursus Kesenian');
        $spreadsheet->getActiveSheet()->setCellValue('CF1', 'Keterampilan Extra');
        $spreadsheet->getActiveSheet()->setCellValue('CG1', 'Asisten Bagian');
        $spreadsheet->getActiveSheet()->setCellValue('CH1', 'id siswa');
        $spreadsheet->getActiveSheet()->setCellValue('CI1', 'Alamat Santri');
        $spreadsheet->getActiveSheet()->setCellValue('CJ1', 'Status Keaktifan');

        $baris = 2;
        $no = 1;
        
        // masukkan datanya
        foreach ($data['siswa'] as $m) {
            $spreadsheet->getActiveSheet()->setCellValue('A' .$baris, $no++);
            $spreadsheet->getActiveSheet()->setCellValue('B' .$baris, $m->nis);
            $spreadsheet->getActiveSheet()->setCellValue('C' .$baris, $m->nama_lengkap);
            $spreadsheet->getActiveSheet()->setCellValue('D' .$baris, $m->kelas);
            $spreadsheet->getActiveSheet()->setCellValue('E' .$baris, $m->konsul);
            $spreadsheet->getActiveSheet()->setCellValue('F' .$baris, $m->rayon);
            $spreadsheet->getActiveSheet()->setCellValue('G' .$baris, $m->alamat);
            $spreadsheet->getActiveSheet()->setCellValue('H' .$baris, $m->nama_arab);
            $spreadsheet->getActiveSheet()->setCellValue('I' .$baris, $m->nama_panggilan);
            $spreadsheet->getActiveSheet()->setCellValue('J' .$baris, $m->nisn);
            $spreadsheet->getActiveSheet()->setCellValue('K' .$baris, $m->tahun_masuk);
            $spreadsheet->getActiveSheet()->setCellValue('L' .$baris, $m->nik);
            $spreadsheet->getActiveSheet()->setCellValue('M' .$baris, $m->no_kis);
            $spreadsheet->getActiveSheet()->setCellValue('N' .$baris, $m->tempat_lahir);
            $spreadsheet->getActiveSheet()->setCellValue('O' .$baris, $m->tanggal_lahir);
            $spreadsheet->getActiveSheet()->setCellValue('P' .$baris, $m->kelurahan);
            $spreadsheet->getActiveSheet()->setCellValue('Q' .$baris, $m->kecamatan);
            $spreadsheet->getActiveSheet()->setCellValue('R' .$baris, $m->kota_kab);
            $spreadsheet->getActiveSheet()->setCellValue('S' .$baris, $m->provinsi);
            $spreadsheet->getActiveSheet()->setCellValue('T' .$baris, $m->kode_pos);
            $spreadsheet->getActiveSheet()->setCellValue('U' .$baris, $m->kewarganegaraan);
            $spreadsheet->getActiveSheet()->setCellValue('V' .$baris, $m->suku);
            $spreadsheet->getActiveSheet()->setCellValue('W' .$baris, $m->ayah);
            $spreadsheet->getActiveSheet()->setCellValue('X' .$baris, $m->pekerjaan_ayah);
            $spreadsheet->getActiveSheet()->setCellValue('Y' .$baris, $m->pend_ayah);
            $spreadsheet->getActiveSheet()->setCellValue('Z' .$baris, $m->agama_ayah);
            $spreadsheet->getActiveSheet()->setCellValue('AA' .$baris, $m->kewarga_ayah);
            $spreadsheet->getActiveSheet()->setCellValue('AB' .$baris, $m->suku_ayah);
            $spreadsheet->getActiveSheet()->setCellValue('AC' .$baris, $m->ormas_ayah);
            $spreadsheet->getActiveSheet()->setCellValue('AD' .$baris, $m->orpol_ayah);
            $spreadsheet->getActiveSheet()->setCellValue('AE' .$baris, $m->kedudukan_ayah);
            $spreadsheet->getActiveSheet()->setCellValue('AF' .$baris, $m->alumni_ayah);
            $spreadsheet->getActiveSheet()->setCellValue('AG' .$baris, $m->ibu);
            $spreadsheet->getActiveSheet()->setCellValue('AH' .$baris, $m->pekerjaan_ibu);
            $spreadsheet->getActiveSheet()->setCellValue('AI' .$baris, $m->pend_ibu);
            $spreadsheet->getActiveSheet()->setCellValue('AJ' .$baris, $m->agama_ibu);
            $spreadsheet->getActiveSheet()->setCellValue('AK' .$baris, $m->kewarga_ibu);
            $spreadsheet->getActiveSheet()->setCellValue('AL' .$baris, $m->suku_ibu);
            $spreadsheet->getActiveSheet()->setCellValue('AM' .$baris, $m->ormas_ibu);
            $spreadsheet->getActiveSheet()->setCellValue('AN' .$baris, $m->orpal_ibu);
            $spreadsheet->getActiveSheet()->setCellValue('AO' .$baris, $m->kedudukan_ibu);
            $spreadsheet->getActiveSheet()->setCellValue('AP' .$baris, $m->alumni_ibu);
            $spreadsheet->getActiveSheet()->setCellValue('AQ' .$baris, $m->wali);
            $spreadsheet->getActiveSheet()->setCellValue('AR' .$baris, $m->hubungan_wali);
            $spreadsheet->getActiveSheet()->setCellValue('AS' .$baris, $m->pekerjaan_wali);
            $spreadsheet->getActiveSheet()->setCellValue('AT' .$baris, $m->pend_wali);
            $spreadsheet->getActiveSheet()->setCellValue('AU' .$baris, $m->agama_wali);
            $spreadsheet->getActiveSheet()->setCellValue('AV' .$baris, $m->kewarga_wali);
            $spreadsheet->getActiveSheet()->setCellValue('AW' .$baris, $m->suku_wali);
            $spreadsheet->getActiveSheet()->setCellValue('AX' .$baris, $m->ormas_wali);
            $spreadsheet->getActiveSheet()->setCellValue('AY' .$baris, $m->orpol_wali);
            $spreadsheet->getActiveSheet()->setCellValue('AZ' .$baris, $m->kedudukan_wali);
            $spreadsheet->getActiveSheet()->setCellValue('BA' .$baris, $m->alumni_wali);
            $spreadsheet->getActiveSheet()->setCellValue('BB' .$baris, $m->telp_wali);
            $spreadsheet->getActiveSheet()->setCellValue('BC' .$baris, $m->telp_ayah);
            $spreadsheet->getActiveSheet()->setCellValue('BD' .$baris, $m->telp_ibu);
            $spreadsheet->getActiveSheet()->setCellValue('BE' .$baris, $m->gol_darah);
            $spreadsheet->getActiveSheet()->setCellValue('BF' .$baris, $m->tinggi_badan);
            $spreadsheet->getActiveSheet()->setCellValue('BG' .$baris, $m->berat_badan);
            $spreadsheet->getActiveSheet()->setCellValue('BH' .$baris, $m->kondisi_rumah);
            $spreadsheet->getActiveSheet()->setCellValue('BI' .$baris, $m->kondisi_ekonomi);
            $spreadsheet->getActiveSheet()->setCellValue('BJ' .$baris, $m->situasi_rumah);
            $spreadsheet->getActiveSheet()->setCellValue('BK' .$baris, $m->letak_rumah);
            $spreadsheet->getActiveSheet()->setCellValue('BL' .$baris, $m->penglihatan_mata);
            $spreadsheet->getActiveSheet()->setCellValue('BM' .$baris, $m->pakai_kacamata);
            $spreadsheet->getActiveSheet()->setCellValue('BN' .$baris, $m->pendengaran_telinga);
            $spreadsheet->getActiveSheet()->setCellValue('BO' .$baris, $m->operasi);
            $spreadsheet->getActiveSheet()->setCellValue('BP' .$baris, $m->kecelakaan);
            $spreadsheet->getActiveSheet()->setCellValue('BQ' .$baris, $m->alergi);
            $spreadsheet->getActiveSheet()->setCellValue('BR' .$baris, $m->kelainan_fisik);
            $spreadsheet->getActiveSheet()->setCellValue('BS' .$baris, $m->sakit_nama);
            $spreadsheet->getActiveSheet()->setCellValue('BT' .$baris, $m->sakit_tahun);
            $spreadsheet->getActiveSheet()->setCellValue('BU' .$baris, $m->sakit_kriteria);
            $spreadsheet->getActiveSheet()->setCellValue('BV' .$baris, $m->sakit_menular);
            $spreadsheet->getActiveSheet()->setCellValue('BW' .$baris, $m->sakit_keterangan);
            $spreadsheet->getActiveSheet()->setCellValue('BX' .$baris, $m->bidang_studi);
            $spreadsheet->getActiveSheet()->setCellValue('BY' .$baris, $m->olah_raga);
            $spreadsheet->getActiveSheet()->setCellValue('BZ' .$baris, $m->kesenian);
            $spreadsheet->getActiveSheet()->setCellValue('CA' .$baris, $m->keterampilan);
            $spreadsheet->getActiveSheet()->setCellValue('CB' .$baris, $m->lain_lain);
            $spreadsheet->getActiveSheet()->setCellValue('CC' .$baris, $m->klub_olah_raga);
            $spreadsheet->getActiveSheet()->setCellValue('CD' .$baris, $m->kursus_bahasa);
            $spreadsheet->getActiveSheet()->setCellValue('CE' .$baris, $m->kursus_kesenian);
            $spreadsheet->getActiveSheet()->setCellValue('CF' .$baris, $m->ketermpilan_extra);
            $spreadsheet->getActiveSheet()->setCellValue('CG' .$baris, $m->asisten_bagian);
            $spreadsheet->getActiveSheet()->setCellValue('CH' .$baris, $m->id);
            $spreadsheet->getActiveSheet()->setCellValue('CI' .$baris, $m->aktif);

            $baris++;
        }

        $filename="Data_Santri-". date('l jS \of F Y h.i.s A') . '.xlsx';

        // Redirect output to a client’s web browser (Xlsx)
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment;filename='.$filename);
        header('Cache-Control: max-age=0');
        
        $writer = IOFactory::createWriter($spreadsheet, 'Xlsx');
        ob_end_clean();
        $writer->save('php://output');
    }
    
    /*
    * FUNGSI UNTUK MUNCULKAN DETAIL DATA SANTRI
    */
    function detail ($id)
    {
        $this->load->model('Siswa_model');
        $data['s'] = $this->Siswa_model->get_siswa($id);
        $detail = $this->Siswa_model->detail_data($id);
        $data['detail'] = $detail;

        $this->load->view('template/header');
        $this->load->view('template/sidebar');
        $this->load->view('siswa/detail', $data);
        $this->load->view('template/footer');
    }

    /*
    * FUNGSI UNTUK MUNCULKAN DATA ALAMAT SANTRI
    */
    function get_alamat()
    {
        $data['title'] = "Data Alamat Santri PMDG Kampus 2";
        $data['datafilter'] = $this->Siswa_model->get_aktif_siswa();

        $this->load->view('siswa/get_alamat', $data);
        $this->load->view('template/footer', $data);
    
    }

    /*
    * FUNGSI UNTUK DOWNLOAD PDF DATA MASING-MASING SANTRI
    */
    function pdf_data($id)
    {
        
        // check if the siswa exists before trying to edit it
        $data['siswa'] = $this->Siswa_model->get_siswa($id);

        if (isset($data['siswa']['id'])) {
        
            // load template rapor default
            $templateProcessor = new \PhpOffice\PhpWord\TemplateProcessor('uploads/angketdata.docx');

            $templateProcessor->setValues(
                array(
                'nis' => $data['siswa']['nis'],
                'tahun_masuk' => $data['siswa']['tahun_masuk'],
                'rayon' => $data['siswa']['rayon'],
                'kelas' => $data['siswa']['kelas'],
                'nama_lengkap' => $data['siswa']['nama_lengkap'], 
                'nama_arab' => $data['siswa']['nama_arab'],
                'nama_panggilan' => $data['siswa']['nama_panggilan'],
                'nik' => $data['siswa']['nik'],
                'no_kis' => $data['siswa']['no_kis'], 
                'nisn' => $data['siswa']['nisn'], 
                'tempat_lahir' => $data['siswa']['tempat_lahir'], 
                'tanggal_lahir' => $data['siswa']['tanggal_lahir'], 
                'konsul' => $data['siswa']['konsul'], 
                'kota_kab' => $data['siswa']['kota_kab'], 
                'kewarganegaraan' => $data['siswa']['kewarganegaraan'], 
                'suku' => $data['siswa']['suku'],
                'desa' => $data['siswa']['kelurahan'],
                'alamat' => $data['siswa']['alamat'],
                'kecamatan' => $data['siswa']['kecamatan'],
                'provinsi' => $data['siswa']['provinsi'],
                'kode_pos' => $data['siswa']['kode_pos'],
                'ayah' => $data['siswa']['ayah'],
                'pekerjaan_ayah' => $data['siswa']['pekerjaan_ayah'],
                'pendidikan_ayah' => $data['siswa']['pend_ayah'],
                'agama_ayah' => $data['siswa']['agama_ayah'],
                'kewarganegaraan_ayah' => $data['siswa']['kewarga_ayah'],
                'suku_ayah' => $data['siswa']['suku_ayah'],
                'ormas_ayah' => $data['siswa']['ormas_ayah'],
                'orpol_ayah' => $data['siswa']['orpol_ayah'],
                'kedudukan_ayah' => $data['siswa']['kedudukan_ayah'],
                'alumni_ayah' => $data['siswa']['alumni_ayah'],
                'telpon_ayah' => $data['siswa']['telp_ayah'],
                'ibu' => $data['siswa']['ibu'],
                'pekerjaan_ibu' => $data['siswa']['pekerjaan_ibu'],
                'pendidikan_ibu' => $data['siswa']['pend_ibu'],
                'agama_ibu' => $data['siswa']['agama_ibu'],
                'kewarganegaraan_ibu' => $data['siswa']['kewarga_ibu'],
                'suku_ibu' => $data['siswa']['suku_ibu'],
                'ormas_ibu' => $data['siswa']['ormas_ibu'],
                'orpol_ibu' => $data['siswa']['orpol_ibu'],
                'kedudukan_ibu' => $data['siswa']['kedudukan_ibu'],
                'alumni_ibu' => $data['siswa']['alumni_ibu'],
                'telpon_ibu' => $data['siswa']['telp_ibu'],
                'wali' => $data['siswa']['wali'],
                'hubungan_wali' => $data['siswa']['hubungan_wali'],
                'pekerjaan_wali' => $data['siswa']['pekerjaan_wali'],
                'pendidikan_wali' => $data['siswa']['pend_wali'],
                'agama_wali' => $data['siswa']['agama_wali'],
                'kewarganegaraan_wali' => $data['siswa']['kewarga_wali'],
                'ormas_wali' => $data['siswa']['ormas_wali'],
                'orpol_wali' => $data['siswa']['orpol_wali'],
                'kedudukan_wali' => $data['siswa']['kedudukan_wali'],
                'alumni_wali' => $data['siswa']['alumni_wali'],
                'golongan_darah' => $data['siswa']['gol_darah'],
                'tinggi_badan' => $data['siswa']['tinggi_badan'],
                'berat_badan' => $data['siswa']['berat_badan'],
                'kondisi_rumah' => $data['siswa']['kondisi_rumah'],
                'kondisi_ekonomi' => $data['siswa']['kondisi_ekonomi'],
                'situasi_rumah' => $data['siswa']['situasi_rumah'],
                'letak_rumah' => $data['siswa']['letak_rumah'],
                'pengelihatan_mata' => $data['siswa']['penglihatan_mata'],
                'pakai_kacamata' => $data['siswa']['pakai_kacamata'],
                'pendengaran_telinga' => $data['siswa']['pendengaran_telinga'],
                'operasi' => $data['siswa']['operasi'],
                'kecelakaan' => $data['siswa']['kecelakaan'],
                'alergi' => $data['siswa']['alergi'],
                'kelainan_fisik' => $data['siswa']['kelainan_fisik'],
                'sakit_tahun' => $data['siswa']['sakit_tahun'],
                'sakit_nama' => $data['siswa']['sakit_nama'],
                'sakit_kriteria' => $data['siswa']['sakit_kriteria'],
                'sakit_menular' => $data['siswa']['sakit_menular'],
                'sakit_keterangan' => $data['siswa']['sakit_keterangan'],
                'bidang_studi' => $data['siswa']['bidang_studi'],
                'olah_raga' => $data['siswa']['olah_raga'],
                'kesenian' => $data['siswa']['kesenian'],
                'keterampilan' => $data['siswa']['keterampilan'],
                'lain_lain' => $data['siswa']['lain_lain'],
                'klub_olah_raga' => $data['siswa']['klub_olah_raga'],
                'kursus_bahasa' => $data['siswa']['kursus_bahasa'],
                'kursus_kesenian' => $data['siswa']['kursus_kesenian'],
                'keterampilan_extra' => $data['siswa']['ketermpilan_extra'],
                'asisten_bagian' => $data['siswa']['asisten_bagian'],

            ));
            
           // save docx
            $templateProcessor->saveAs('temp/' . 'result_angket' . '.docx');

            $file_doc = 'temp/' . 'result_angket' . '.docx';
            $file_html = 'temp/' . 'result_angket' . '.html';

            $filename = 'Data Santri ' . $data['siswa']['nama_lengkap']. ' Kelas '. $data['siswa']['kelas'] . ' Tahun ' . $_SESSION['tahun'] . ' Semester ' . $_SESSION['semester'] .'.docx';

            header('Content-type:  application/pdf');
            header('Content-Length: ' . filesize($file_doc));
            header('Content-Disposition: attachment; filename="' . $filename);
            readfile($file_doc);

            ignore_user_abort(true);

            // hapus file di temp
            unlink($file_html);
            unlink($file_doc);

        }
        
    }

     ///////////////////////////////////////////////////// DATA SAUDARA ////////////////////////////////////////////////////////////////////

    /*
     * Tambah Saudara Siswa
     */
    function input_data_saudara(){
        
        $stambuk = $_POST['stambuk'];
       
        // Ambil data yang dikirim dari form
		$nama = $_POST['nama']; // Ambil data nama dan masukkan ke variabel nama
		$kelamin = $_POST['kelamin']; // Ambil data kelamin dan masukkan ke variabel kelamin
		$umur = $_POST['umur']; // Ambil data umur dan masukkan ke variabel umur
        $pend_terakhir = $_POST['pend_terakhir']; // Ambil data pend_terakhir dan masukkan ke variabel pend_terakhir
        $pekerjaan = $_POST['pekerjaan']; // Ambil data pekerjaan dan masukkan ke variabel pekerjaan
        $status = $_POST['status']; // Ambil data status dan masukkan ke variabel status
        
		$data = array();
		
		$index = 0; // Set index array awal dengan 0

		foreach($umur as $dataumur){ // Kita buat perulangan berdasarkan umur sampai data terakhir
			array_push($data, array(
                'stambuk_santri'=>$stambuk,
				'umur'=>$dataumur,
				'nama'=>$nama[$index],  // Ambil dan set data nama sesuai index array dari $index
                'kelamin'=>$kelamin[$index],  // Ambil dan set data kelamin sesuai index array dari $index
				'pend_terakhir'=>$pend_terakhir[$index],  // Ambil dan set data pend_terakhir sesuai index array dari $index
				'pekerjaan'=>$pekerjaan[$index],  // Ambil dan set data pekerjaan sesuai index array dari $index
                'status'=>$status[$index],  // Ambil dan set data status sesuai index array dari $index
			));
			
			$index++;
		}
		
        $aksi = $this->db->insert_batch('siswa_saudara',$data);
		
		// Cek apakah query insert nya sukses atau gagal
		if($aksi){ // Jika sukses
            $this->session->set_flashdata('add', 'Anda berhasil menambahkan data saudara <strong>' . $nama . '</strong>');
            redirect('siswa/edit/'. $stambuk);
		}else{ // Jika gagal
			echo "<script>alert('Data gagal disimpan');window.location = '".base_url('siswa/edit/'. $stambuk)."';</script>";
		}
     }

     /*
     * Deleting saudara siswa
     */
    function delete_saudara($id)
    {
        $saudara = $this->Siswa_model->get_saudara_siswa($id);
        $stambuk = $saudara['stambuk_santri'];

        // check if the siswa exists before trying to delete it
        if (isset($saudara['id'])) {
            $this->session->set_flashdata('hapus', 'Anda berhasil menghapus data <strong>' . $saudara['nama'] . '</strong>');
            $this->Siswa_model->delete_saudara_siswa($id);
            redirect('siswa/edit/'. $stambuk);
        } else
            show_error('The siswa you are trying to delete does not exist.');
    }

    ///////////////////////////////////////////////////// AUTOSELECT DATA ALAMAT ////////////////////////////////////////////////////////////////////
    
    function add_ajax_kab($nama_prov){
        $query = $this->db->query("SELECT DISTINCT kabupaten FROM tb_kategori_alamat WHERE (provinsi) = '$nama_prov'");
        $data = "<option value=''>- Select Kabupaten -</option>";
        foreach ($query->result() as $value) {
            $data .= "<option value='".$value->kabupaten."'>".$value->kabupaten."</option>";
        }
        echo $data;
    }
    
    function add_ajax_kec($id_kab){
        $query = $this->db->get_where('wilayah_kecamatan',array('kabupaten_id'=>$id_kab));
        $data = "<option value=''> - Pilih Kecamatan - </option>";
        foreach ($query->result() as $value) {
            $data .= "<option value='".$value->id."'>".$value->nama."</option>";
        }
        echo $data;
    }
    
    function add_ajax_des($id_kec){
        $query = $this->db->get_where('wilayah_desa',array('kecamatan_id'=>$id_kec));
        $data = "<option value=''> - Pilih Desa - </option>";
        foreach ($query->result() as $value) {
            $data .= "<option value='".$value->id."'>".$value->nama."</option>";
        }
        echo $data;
    }
}
