<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Helper\Sample;

class Siswa_nonaktif extends CI_Controller
{
    
    function __construct()
    {
        parent::__construct();
        $this->load->model('Siswa_model');

        // cek user login
        check_login();
    }

    /*
     * Listing of siswa
     */
    function index()
    {
        $data['siswa'] = $this->Siswa_model->get_nonaktif_siswa();

        $data['_view'] = 'siswa_nonaktif/index';

        $this->load->view('template/header', $data);
        $this->load->view('template/sidebar', $data);
        $this->load->view('siswa_nonaktif/index', $data);
        $this->load->view('template/footer', $data);
    }

}  