<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Pelanggaran extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Siswa_model');
        $this->load->model('Kategori_model');
        $this->load->model('Pelanggaran_kmi_model');

        // cek user login
        check_login();
    }

    /*
     * Listing of tabel data santri
     */
    function index()
    {
        // ambil data santri aktif
        $data['siswa'] = $this->Siswa_model->get_all_siswa();

        $data['_view'] = 'kmi/pelanggaran/index';

        $this->load->view('template/header', $data);
        $this->load->view('template/sidebar', $data);
        $this->load->view('kmi/pelanggaran/index', $data);
        $this->load->view('template/footer', $data);
    }

    /*
     * Listing of detail pelanggaran siswa
     */
    function detail ($id)
    {
        // periksa bahwa data santri itu ada
        $data['siswa'] = $this->Siswa_model->get_siswa($id);

        if (isset($data['siswa']['id'])) {
                $data['datafilter'] =$this->Pelanggaran_kmi_model->filter_by_id_siswa($id);
                $data['detail'] =$this->Siswa_model->detail_data($id);
             
                $data['_view'] = 'pelanggaran/detail';
                $this->load->view('template/header', $data);
                $this->load->view('template/sidebar', $data);
                $this->load->view('kmi/pelanggaran/detail', $data);
                $this->load->view('template/footer', $data);
        } else
        show_error('The siswa you are trying to edit does not exist.');
    }

    /*
     * Function for input pelanggaran siswa
     */
    function input_pelanggaran($id)
    {
        // periksa bahwa data santri itu ada
        $data['siswa'] = $this->Siswa_model->get_siswa($id);
        // munculkan detail data santri
        $data['detail'] = $this->Siswa_model->detail_data($id);

        if(isset($data['siswa']['id']))
        {
            $this->load->library('form_validation');
			$this->form_validation->set_rules('nama_pelanggaran','Nama Pelanggaran','required');

            if($this->form_validation->run()) {
               
                $id_siswa =  $this->input->post('id_siswa');
                $id_penghukum = $this->input->post('penghukum');
                $nama_lengkap = $this->input->post('nama_lengkap');
                $nama_pelanggaran = $this->input->post('nama_pelanggaran');
                $kategori_pelanggaran = $this->input->post('kategori');
                $poin_pelanggaran = $this->input->post('poin');
                $keterangan = $this->input->post('keterangan');
        
        
                $data = array(
                    'id_siswa' => $id_siswa,
                    'id_penghukum' => $id_penghukum,
                    'nama_pelanggaran' => $nama_pelanggaran,
                    'kategori_pelanggaran' => $kategori_pelanggaran,
                    'poin_pelanggaran' => $poin_pelanggaran,
                    'poin_santri' => $poin_pelanggaran,
                    'keterangan' => $keterangan,);
                    
        
                $this->Pelanggaran_kmi_model->tambah_pelanggaran($data);
                $this->session->set_flashdata('berhasil', 'Anda berhasil menambahkan data pelanggaran <strong>' . $nama_lengkap . '</strong>' . ' berupa <strong>' . $nama_pelanggaran . '</strong>' );
                redirect('kmi/pelanggaran');
            }
            else
            {
                $data['pelanggaranringan'] = $this->Kategori_model->get_pelanggaran_kmi_ringan();
                $data['pelanggaransedang'] = $this->Kategori_model->get_pelanggaran_kmi_sedang();
                $data['pelanggaranberat'] = $this->Kategori_model->get_pelanggaran_kmi_berat();
                $data['stafkmi'] = $this->Kategori_model->get_staf_kmi();
           
                $data['_view'] = 'kmi/pelanggaran/input_pelanggaran';
                $this->load->view('template/header');
                $this->load->view('template/sidebar');
                $this->load->view('kmi/pelanggaran/input_pelanggaran', $data);
                $this->load->view('template/footer');
            }
        }
        else
            show_error('The Pelanggaran Santri you are trying to input does not exist.');
    }

    /*
     * Function for Editing a pelanggaran santri
     */
    function edit_pelanggaran($id_pelanggaran)
    {   
        // check if the pelanggaran exists before trying to edit it
        $data['pelanggaran'] = $this->Pelanggaran_kmi_model->get_pelanggaran($id_pelanggaran);

        if(isset($data['pelanggaran']['id_pelanggaran']))
        {
            $this->load->library('form_validation');
			$this->form_validation->set_rules('penghukum','Penghukum','required');

            $id_pelanggaran = $data['pelanggaran']['id_pelanggaran'];
            $id_siswa = $data['pelanggaran']['id_siswa'];
            $data['detail'] = $this->Siswa_model->detail_data($id_siswa);
		
			if($this->form_validation->run())     
            {   
                $params = array(
                    'id_penghukum' => $this->input->post('penghukum'),
                    'nama_pelanggaran' => $this->input->post('nama_pelanggaran'),
                    'kategori_pelanggaran' => $this->input->post('kategori'),
                    'poin_pelanggaran' => $this->input->post('poin'),
                    'poin_santri' => $this->input->post('poin'),
                    'keterangan' => $this->input->post('keterangan'),
                );

                $nama_siswa = $this->input->post('nama_lengkap');

                $this->Pelanggaran_kmi_model->update_pelanggaran($id_pelanggaran,$params);
                $this->session->set_flashdata('berhasil', 'Anda berhasil mengubah data hukuman pelanggaran <strong>' . $nama_siswa . '</strong>' . ' menjadi <strong>' . $this->input->post('nama_pelanggaran') . '</strong>');

                redirect(base_url('kmi/pelanggaran/detail/' . $id_siswa)) ;
            }
            else
            {
                $data['pelanggaranringan'] = $this->Kategori_model->get_pelanggaran_kmi_ringan();
                $data['pelanggaransedang'] = $this->Kategori_model->get_pelanggaran_kmi_sedang();
                $data['pelanggaranberat'] = $this->Kategori_model->get_pelanggaran_kmi_berat();
                $data['stafkmi'] = $this->Kategori_model->get_staf_kmi();

                $data['_view'] = 'kmi/pelanggaran/edit_pelanggaran';
                $this->load->view('template/header',$data);
                $this->load->view('template/sidebar',$data);
                $this->load->view('kmi/pelanggaran/edit_pelanggaran',$data);
                $this->load->view('template/footer',$data);
            }
        }
        else
            show_error('The Pelanggaran Santri you are trying to edit does not exist.');
    } 

    /*
     * Function of hapus pelanggaran siswa
     */
    function hapus_pelanggaran($id_pelanggaran)
    {
        // check if the pelanggaran exists before trying to edit it
        $data['pelanggaran'] = $this->Pelanggaran_kmi_model->get_pelanggaran($id_pelanggaran);

        if(isset($data['pelanggaran']['id_pelanggaran']))
        {
            $this->Pelanggaran_kmi_model->delete_pelanggaran($id_pelanggaran);
            $this->session->set_flashdata('hapus', 'Anda berhasil menghapus data pelanggaran <strong>' .  $data['pelanggaran']['nama_lengkap'] . '</strong>' . ' berupa <strong>' .  $data['pelanggaran']['nama_pelanggaran'] . '</strong>' );
            redirect(base_url('kmi/pelanggaran/detail/' . $data['pelanggaran']['id_siswa'])) ;
        } else
        show_error('The siswa you are trying to delete does not exist.');
    }
    
    /*
     * Function of print pdf pelanggaran siswa
     */
    function print()
    {
        $id_siswa = $this->input->post('id_siswa');
        $filterid = $this->input->post('print');

        if ($filterid == 1) {
            $data['datafilter'] =$this->Pelanggaran_kmi_model->filter_by_id_siswa($id_siswa);
            $data['detail'] =$this->Siswa_model->detail_data($id_siswa);
        
            $data['_view'] = 'pelanggaran/detail';
 
            $this->load->view('kmi/pelanggaran/print_laporan', $data);
            $this->load->view('template/footer', $data);
        }
    }

    /*
     * Listing of form Filter pelanggaran siswa
     */
    function form_filter_tanggal ()
    {
        $this->load->view('template/header');
        $this->load->view('template/sidebar');
        $this->load->view('kmi/pelanggaran/form_filter_tanggal');
        $this->load->view('template/footer');
    }
   
    /*
     * Function of Submit form Filter pelanggaran siswa
     */
    function filterbytanggal()
    {
        $tanggalawal = $this->input->post('tanggalawal');
        $tanggalakhir = $this->input->post('tanggalakhir');
        $nilaitanggal = $this->input->post('nilaitanggal');

           
        if ($nilaitanggal == 1) {
            $data['title'] = "Data Santri yang melanggar dari tanggal '. <?php echo format_tanggal ($tanggalawal) ?> .'  hingga '. <?php echo format_tanggal ($tanggalakhir) ?>.'";
            $data['tanggalawal'] = $tanggalawal;
            $data['tanggalakhir'] = $tanggalakhir;

           
            $data['dataterlambat'] =$this->Pelanggaran_kmi_model->filter_by_tanggal_terlambat($tanggalawal,$tanggalakhir);
            $data['datatidakpiket'] =$this->Pelanggaran_kmi_model->filter_by_tanggal_tidak_piket_kelas($tanggalawal,$tanggalakhir);
            $data['datakeluarkelas'] =$this->Pelanggaran_kmi_model->filter_by_tanggal_keluar_kelas($tanggalawal,$tanggalakhir);
            $data['datatidakpakaikaoskaki'] =$this->Pelanggaran_kmi_model->filter_by_tanggal_tidak_pakai_kaos_kaki($tanggalawal,$tanggalakhir);
            $data['datatidakmuajjah'] =$this->Pelanggaran_kmi_model->filter_by_tanggal_tidak_muajjah($tanggalawal,$tanggalakhir);
            $data['datatidakizinpakaisandal'] =$this->Pelanggaran_kmi_model->filter_by_tanggal_tidak_izin_pakai_sendal($tanggalawal,$tanggalakhir);
            $data['datatidakmembawatassepatu'] =$this->Pelanggaran_kmi_model->filter_by_tanggal_tidak_membawa_tassepatu($tanggalawal,$tanggalakhir);
            $data['datatiddakmengumpulkaninsya'] =$this->Pelanggaran_kmi_model->filter_by_tanggal_tidak_mengumpulkan_insya($tanggalawal,$tanggalakhir);
            $data['datamembawabarangterlarang'] =$this->Pelanggaran_kmi_model->filter_by_tanggal_membawa_barang_terlarang($tanggalawal,$tanggalakhir);
            $data['datamenerlambatkandiri'] =$this->Pelanggaran_kmi_model->filter_by_tanggal_menerlambatkan_diri($tanggalawal,$tanggalakhir);
            $data['dataghoibkelas'] =$this->Pelanggaran_kmi_model->filter_by_tanggal_ghoib_kelas($tanggalawal,$tanggalakhir);
          
            $this->load->view('template/header', $data);
            $this->load->view('template/sidebar', $data);
            $this->load->view('kmi/pelanggaran/print_grafik', $data);
            $this->load->view('template/footer', $data);
    
        }
    }

     /*
     * Listing Of Input Massal
     */
    function input_massal()
    {   
        $data['siswa'] = $this->Siswa_model->get_aktif_siswa();

        $data['pelanggaranringan'] = $this->Kategori_model->get_pelanggaran_kmi_ringan();
        $data['pelanggaransedang'] = $this->Kategori_model->get_pelanggaran_kmi_sedang();
        $data['pelanggaranberat'] = $this->Kategori_model->get_pelanggaran_kmi_berat();
        $data['stafkmi'] = $this->Kategori_model->get_staf_kmi();

        $this->load->view('template/header',$data);
        $this->load->view('template/sidebar',$data);
        $this->load->view('kmi/pelanggaran/input_massal',$data);
        $this->load->view('template/footer',$data);
    }
    
     /*
     * Function for Submit Input Massal
     */
    function simpan_massal()
    {
        $result = $this->input->post('id_siswa[]');

        $params = array();
        $nama_pelanggaran = $this->input->post('nama_pelanggaran');
        $kategori_pelanggaran = $this->input->post('kategori');
        $poin_pelanggaran = $this->input->post('poin');
        $id_penghukum = $this->input->post('penghukum');
        $keterangan = $this->input->post('keterangan');

        foreach($result as $result){
            
            $id_siswa = $result;

            array_push($params, [
                'nama_pelanggaran' => $nama_pelanggaran,
                'kategori_pelanggaran' => $kategori_pelanggaran,
                'id_penghukum' => $id_penghukum,
                'poin_pelanggaran' => $poin_pelanggaran,
                'poin_santri' => $poin_pelanggaran,
                'keterangan' => $keterangan,
                'id_siswa' => $id_siswa
            ]);

        $jumlahdata = count($params); 

        $this->session->set_flashdata('berhasil', 'Anda berhasil menambahkan data pelanggaran <strong>'.$nama_pelanggaran.'</strong> sejumlah <strong>'.$jumlahdata.' Santri </strong>');
        }

        $this->db->insert_batch('record_pelanggaran_kmi', $params);
        redirect('kmi/pelanggaran/tabel_pelanggaran');
    }

    /*
     * Listing of newest pelanggaran siswa
     */
    function tabel_pelanggaran()
    {
        $data['pelanggaran_siswa'] = $this->Pelanggaran_kmi_model->get_tabel_pelanggaran_siswa();

        $data['_view'] = 'kmi/pelanggaran/tabel_indeks_pelanggaran';

        $this->load->view('template/header', $data);
        $this->load->view('template/sidebar', $data);
        $this->load->view('kmi/pelanggaran/tabel_indeks_pelanggaran', $data);
        $this->load->view('template/footer', $data);
    }

    /*
     * Listing of filter pelanggaran siswa
     */
    function filter ()
    {
        $data['pelanggaranringan'] = $this->Kategori_model->get_pelanggaran_kmi_ringan();
        $data['pelanggaransedang'] = $this->Kategori_model->get_pelanggaran_kmi_sedang();
        $data['pelanggaranberat'] = $this->Kategori_model->get_pelanggaran_kmi_berat();
        $data['stafkmi'] = $this->Kategori_model->get_staf_kmi();
        $data['rayon'] = $this->Kategori_model->get_rayon();

        $this->load->view('template/header');
        $this->load->view('template/sidebar');
        $this->load->view('kmi/filter/index_pelanggaran', $data);
        $this->load->view('template/footer');
    }

    /*
     * Function for Submit Filter Perkategori
     */
    function filterbykategori()
    {
        $nama_pelanggaran = $this->input->post('nama_pelanggaran');
        $penghukum = $this->input->post('penghukum');
        $tanggalawal = $this->input->post('tanggalawal');
        $tanggalakhir = $this->input->post('tanggalakhir');
        $rayon = $this->input->post('rayon');

        $nilaipelanggaran = $this->input->post('nilaipelanggaran');
        $nilaipenghukum = $this->input->post('nilaipenghukum');
        $nilaitanggal = $this->input->post('nilaitanggal');
        $nilairayon = $this->input->post('nilairayon');
    
        if ($nilaipelanggaran == 1) {
            $data['title'] = "Data Santri Yang Melanggar Pelanggaran $nama_pelanggaran";
            $data['datafilter'] =$this->Pelanggaran_kmi_model->filter_by_pelanggaran($nama_pelanggaran);

            $this->load->view('kmi/filter/print_laporan', $data);
            $this->load->view('template/footer', $data);
    
        }

        if ($nilaipenghukum == 1) {
            $data['title'] = "Data Santri Yang Mendapat Hukuman Oleh $penghukum";
            $data['datafilter'] =$this->Pelanggaran_kmi_model->filter_by_penghukum($penghukum);
    
            $this->load->view('kmi/filter/print_laporan', $data);
            $this->load->view('template/footer', $data);
    
        }

        if ($nilaitanggal == 1) {
            $data['title'] = "Data Santri Yang Melanggar Dari $tanggalawal Sampai $tanggalakhir" ;
            $data['datafilter'] =$this->Pelanggaran_kmi_model->filter_by_tanggal($tanggalawal,$tanggalakhir);
    
            $this->load->view('kmi/filter/print_laporan', $data);
            $this->load->view('template/footer', $data);
    
        }

        if ($nilairayon == 1) {
            $data['title'] = "Data Santri Yang Melanggar Dari Rayon $rayon";
            $data['datafilter'] =$this->Pelanggaran_kmi_model->filterpelanggaran_by_rayon($rayon);
    
            $this->load->view('kmi/filter/print_laporan', $data);
            $this->load->view('template/footer', $data);
    
        }
    }

    /*
     * Javasript autofill Kategori Pelanggaran
     */
    function fill_kategori_pelanggaran(){
        $nama_pelanggaran = $_POST['nama_pelanggaran'];
        $s = "SELECT * FROM tb_pelanggaran_kmi WHERE nama_pelanggaran='$nama_pelanggaran'";

        $res = $this->db->query($s)->row_array();
        echo json_encode($res);
    }

    //////////////////////////////////////////////////// FUNGSI UNTUK TABEL PELANGGARAN ////////////////////////////////////////////////////////////////

    /*
     * Function for Editing a pelanggaran santri
     */
    function edit_pelanggaran_tabel($id_pelanggaran)
    {   
        // check if the pelanggaran exists before trying to edit it
        $data['pelanggaran'] = $this->Pelanggaran_kmi_model->get_pelanggaran($id_pelanggaran);

        if(isset($data['pelanggaran']['id_pelanggaran']))
        {
            $this->load->library('form_validation');
			$this->form_validation->set_rules('penghukum','Penghukum','required');

            $id_pelanggaran = $data['pelanggaran']['id_pelanggaran'];
            $id_siswa = $data['pelanggaran']['id_siswa'];
            $data['detail'] = $this->Siswa_model->detail_data($id_siswa);
		
			if($this->form_validation->run())     
            {   
                $params = array(
                    'id_penghukum' => $this->input->post('penghukum'),
                    'nama_pelanggaran' => $this->input->post('nama_pelanggaran'),
                    'kategori_pelanggaran' => $this->input->post('kategori'),
                    'poin_pelanggaran' => $this->input->post('poin'),
                    'poin_santri' => $this->input->post('poin'),
                    'keterangan' => $this->input->post('keterangan'),
                );

                $nama_siswa = $this->input->post('nama_lengkap');

                $this->Pelanggaran_kmi_model->update_pelanggaran($id_pelanggaran,$params);
                $this->session->set_flashdata('berhasil', 'Anda berhasil mengubah data hukuman pelanggaran <strong>' . $nama_siswa . '</strong>' . ' menjadi <strong>' . $this->input->post('nama_pelanggaran') . '</strong>');

                redirect(base_url('kmi/pelanggaran/tabel_pelanggaran')) ;
            }
            else
            {
                $data['pelanggaranringan'] = $this->Kategori_model->get_pelanggaran_kmi_ringan();
                $data['pelanggaransedang'] = $this->Kategori_model->get_pelanggaran_kmi_sedang();
                $data['pelanggaranberat'] = $this->Kategori_model->get_pelanggaran_kmi_berat();
                $data['stafkmi'] = $this->Kategori_model->get_staf_kmi();

                $data['_view'] = 'kmi/pelanggaran/edit_pelanggaran_tabel';
                $this->load->view('template/header',$data);
                $this->load->view('template/sidebar',$data);
                $this->load->view('kmi/pelanggaran/edit_pelanggaran_tabel',$data);
                $this->load->view('template/footer',$data);
            }
        }
        else
            show_error('The Pelanggaran Santri you are trying to edit does not exist.');
    } 

    /*
     * Function of hapus pelanggaran siswa
     */
    function hapus_pelanggaran_tabel($id_pelanggaran)
    {
        // check if the pelanggaran exists before trying to edit it
        $data['pelanggaran'] = $this->Pelanggaran_kmi_model->get_pelanggaran($id_pelanggaran);

        if(isset($data['pelanggaran']['id_pelanggaran']))
        {
            $this->Pelanggaran_kmi_model->delete_pelanggaran($id_pelanggaran);
            $this->session->set_flashdata('hapus', 'Anda berhasil menghapus data pelanggaran <strong>' .  $data['pelanggaran']['nama_lengkap'] . '</strong>' . ' berupa <strong>' .  $data['pelanggaran']['nama_pelanggaran'] . '</strong>' );
            redirect(base_url('kmi/pelanggaran/tabel_pelanggaran')) ;
        } else
        show_error('The siswa you are trying to delete does not exist.');
    }


    //////////////////////////////////////////////////// FUNGSI UNTUK TABEL KATEGORI PELANGGARAN ////////////////////////////////////////////////////////////////

    /*
     * Function for input pelanggaran siswa
     */
    function tambah_kategori_pelanggaran()
    {
        // ambil data santri aktif
        $data['pelanggaran'] = $this->Pelanggaran_kmi_model->get_all_kategori_pelanggaran();

        $this->load->library('form_validation');
        $this->form_validation->set_rules('nama_pelanggaran','Nama Pelanggaran','required');

        if($this->form_validation->run()) {
            
            $nama_pelanggaran = $this->input->post('nama_pelanggaran');
            $kategori_pelanggaran = $this->input->post('kategori');
    
            $data = array(
                'nama_pelanggaran' => $nama_pelanggaran,
                'kategori' => $kategori_pelanggaran,);
                
            $this->Pelanggaran_kmi_model->tambah_kategori_pelanggaran($data);
            $this->session->set_flashdata('berhasil', 'Anda berhasil menambahkan data pelanggaran <strong>' . $nama_pelanggaran . '</strong>' . ' dengan kategori <strong>' . $kategori_pelanggaran . '</strong>' );
            redirect('kmi/pelanggaran/tambah_kategori_pelanggaran');
        }
        else
        {
            $data['_view'] = 'kmi/pelanggaran/tambah_kategori_pelanggaran';
            $this->load->view('template/header');
            $this->load->view('template/sidebar');
            $this->load->view('kmi/pelanggaran/tambah_kategori_pelanggaran', $data);
            $this->load->view('template/footer');
        }
    }

    /*
     * Function for Editing a KATEGORI pelanggaran santri
     */
    function edit_kategori_pelanggaran($id_kategori)
    {   
        // check if the pelanggaran exists before trying to edit it
        $data['kategori_pelanggaran'] = $this->Pelanggaran_kmi_model->get_kategori_pelanggaran($id_kategori);

        if(isset($data['kategori_pelanggaran']['id']))
        {
            $this->load->library('form_validation');
            $this->form_validation->set_rules('nama_pelanggaran','Nama Pelanggaran','required');


            $id_kategori = $data['kategori_pelanggaran']['id'];
          
			if($this->form_validation->run())     
            {   
                $nama_pelanggaran = $this->input->post('nama_pelanggaran');
                $kategori_pelanggaran = $this->input->post('kategori');

                $data = array(
                    'nama_pelanggaran' => $nama_pelanggaran,
                    'kategori' => $kategori_pelanggaran,);

                $this->Pelanggaran_kmi_model->update_kategori_pelanggaran($id_kategori,$data);
                $this->session->set_flashdata('berhasil', 'Anda berhasil mengubah data pelanggaran <strong>' . $nama_pelanggaran . '</strong>' . ' dengan kategori <strong>' . $kategori_pelanggaran . '</strong>' );

                redirect(base_url('kmi/pelanggaran/tambah_kategori_pelanggaran')) ;
            }
            else
            {
                
                $data['_view'] = 'kmi/pelanggaran/edit_kategori_pelanggaran';
                $this->load->view('template/header',$data);
                $this->load->view('template/sidebar',$data);
                $this->load->view('kmi/pelanggaran/edit_kategori_pelanggaran',$data);
                $this->load->view('template/footer',$data);
            }
        }
        else
            show_error('The Kategori Pelanggaran Santri you are trying to edit does not exist.');
    }

    /*
     * Function of hapus KATEGORI pelanggaran siswa
     */
    function hapus_kategori_pelanggaran($id_kategori)
    {
        // check if the pelanggaran exists before trying to edit it
        $data['kategori_pelanggaran'] = $this->Pelanggaran_kmi_model->get_kategori_pelanggaran($id_kategori);

        if(isset($data['kategori_pelanggaran']['id']))
        {
            $this->Pelanggaran_kmi_model->delete_kategori_pelanggaran($id_kategori);
            $this->session->set_flashdata('hapus', 'Anda berhasil menghapus data pelanggaran <strong>' .  $data['kategori_pelanggaran']['nama_pelanggaran'] . '</strong>' . ' dengan kategori <strong>' .  $data['kategori_pelanggaran']['kategori'] . '</strong>' );
            redirect(base_url('kmi/pelanggaran/tambah_kategori_pelanggaran')) ;
        } else
        show_error('The kategori pelanggaran you are trying to delete does not exist.');
    }
}
