<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Pelanggaran extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Siswa_model');
        $this->load->model('Kategori_model');
        $this->load->model('Pelanggaran_pengasuhan_model');

        // cek user login
        check_login();
    }

    ///////////////////////////////////////////////////// CRUD PELANGGARAN SANTRI ////////////////////////////////////////////////////////////////

    /*
     * Listing of tabel data santri
     */
    function index()
    {
        // ambil data santri aktif
        $data['siswa'] = $this->Siswa_model->get_aktif_siswa();

        $data['_view'] = 'pengasuhan/pelanggaran/index';

        $this->load->view('template/header', $data);
        $this->load->view('template/sidebar', $data);
        $this->load->view('pengasuhan/pelanggaran/index', $data);
        $this->load->view('template/footer', $data);
    }

    /*
     * Listing of detail pelanggaran siswa
     */
    function detail ($id)
    {
        // periksa bahwa data santri itu ada
        $data['siswa'] = $this->Siswa_model->get_siswa($id);

        if (isset($data['siswa']['id'])) {
                $data['datafilter'] =$this->Pelanggaran_pengasuhan_model->filter_by_id_siswa($id);
                $data['detail'] =$this->Siswa_model->detail_data($id);
             
                $data['_view'] = 'pengasuhan/pelanggaran/detail';
                $this->load->view('template/header', $data);
                $this->load->view('template/sidebar', $data);
                $this->load->view('pengasuhan/pelanggaran/detail', $data);
                $this->load->view('template/footer', $data);
        } else
        show_error('The siswa you are trying to edit does not exist.');
    }

    /*
     * Function for input pelanggaran santri
     */
    function input_pelanggaran($id)
    {
        // periksa bahwa data santri itu ada
        $data['siswa'] = $this->Siswa_model->get_siswa($id);
        // munculkan detail data santri
        $data['detail'] = $this->Siswa_model->detail_data($id);

        if(isset($data['siswa']['id']))
        {
            $this->load->library('form_validation');
			$this->form_validation->set_rules('nama_pelanggaran','Nama Pelanggaran','required');

            if($this->form_validation->run()) {
               
                $id_siswa =  $this->input->post('id_siswa');
                $id_penghukum = $this->input->post('penghukum');
                $nama_lengkap = $this->input->post('nama_lengkap');
                $nama_pelanggaran = $this->input->post('nama_pelanggaran');
                $kategori_pelanggaran = $this->input->post('kategori');
                $poin_pelanggaran = $this->input->post('poin');
                $keterangan = $this->input->post('keterangan');
        
                $data = array(
                    'id_siswa' => $id_siswa,
                    'id_penghukum' => $id_penghukum,
                    'nama_pelanggaran' => $nama_pelanggaran,
                    'kategori_pelanggaran' => $kategori_pelanggaran,
                    'poin_pelanggaran' => $poin_pelanggaran,
                    'keterangan' => $keterangan,);
                    
                $datapoint = array(
                    'poin_santri' => $poin_pelanggaran,
                   );
        
                $this->Pelanggaran_pengasuhan_model->tambah_pelanggaran($data);
                $this->Pelanggaran_pengasuhan_model->tambah_poin_pelanggaran($id_siswa, $datapoint, $poin_pelanggaran);

                $this->session->set_flashdata('berhasil', 'Anda berhasil menambahkan data pelanggaran <strong>' . $nama_lengkap . '</strong>' . ' berupa <strong>' . $nama_pelanggaran . '</strong>' );
                redirect('pengasuhan/pelanggaran');
            }
            else
            {
                $data['pelanggaranringan'] = $this->Kategori_model->get_pelanggaran_pengasuhan_ringan();
                $data['pelanggaransedang'] = $this->Kategori_model->get_pelanggaran_pengasuhan_sedang();
                $data['pelanggaranberat'] = $this->Kategori_model->get_pelanggaran_pengasuhan_berat();
                $data['penghukumpengasuhan'] = $this->Kategori_model->get_penghukum_pengasuhan();
                $data['penghukumkeamanan'] = $this->Kategori_model->get_penghukum_keamanan();
                $data['penghukumrayon'] = $this->Kategori_model->get_penghukum_pengurus_rayon();
           
                $data['_view'] = 'pengasuhan/pelanggaran/input_pelanggaran';
                $this->load->view('template/header');
                $this->load->view('template/sidebar');
                $this->load->view('pengasuhan/pelanggaran/input_pelanggaran', $data);
                $this->load->view('template/footer');
            }
        }
        else
            show_error('The Pelanggaran Santri you are trying to input does not exist.');
    }

    /*
     * Function for edit pelanggaran santri
     */
    function edit_pelanggaran($id_pelanggaran)
    {   
        // check if the pelanggaran exists before trying to edit it
        $data['pelanggaran'] = $this->Pelanggaran_pengasuhan_model->get_pelanggaran($id_pelanggaran);

        if(isset($data['pelanggaran']['id_pelanggaran']))
        {
            $this->load->library('form_validation');
			$this->form_validation->set_rules('penghukum','Penghukum','required');

            $id_pelanggaran = $data['pelanggaran']['id_pelanggaran'];
            $id_siswa = $data['pelanggaran']['id_siswa'];
            $data['detail'] = $this->Siswa_model->detail_data($id_siswa);
		
			if($this->form_validation->run())     
            {   
                $params = array(
                    'id_penghukum' => $this->input->post('penghukum'),
                    'nama_pelanggaran' => $this->input->post('nama_pelanggaran'),
                    'kategori_pelanggaran' => $this->input->post('kategori'),
                    'poin_pelanggaran' => $this->input->post('poin'),
                    'keterangan' => $this->input->post('keterangan'),
                );

                $nama_siswa = $this->input->post('nama_lengkap');

                $this->Pelanggaran_pengasuhan_model->update_pelanggaran($id_pelanggaran,$params);
                $this->session->set_flashdata('berhasil', 'Anda berhasil mengubah data hukuman pelanggaran <strong>' . $nama_siswa . '</strong>' . ' menjadi <strong>' . $this->input->post('nama_pelanggaran') . '</strong>');

                redirect(base_url('pengasuhan/pelanggaran/detail/' . $id_siswa)) ;
            }
            else
            {
                $data['pelanggaranringan'] = $this->Kategori_model->get_pelanggaran_pengasuhan_ringan();
                $data['pelanggaransedang'] = $this->Kategori_model->get_pelanggaran_pengasuhan_sedang();
                $data['pelanggaranberat'] = $this->Kategori_model->get_pelanggaran_pengasuhan_berat();
                $data['penghukumpengasuhan'] = $this->Kategori_model->get_penghukum_pengasuhan();
                $data['penghukumkeamanan'] = $this->Kategori_model->get_penghukum_keamanan();

                $data['_view'] = 'pengasuhan/pelanggaran/edit_pelanggaran';
                $this->load->view('template/header',$data);
                $this->load->view('template/sidebar',$data);
                $this->load->view('pengasuhan/pelanggaran/edit_pelanggaran',$data);
                $this->load->view('template/footer',$data);
            }
        }
        else
            show_error('The Pelanggaran Santri you are trying to edit does not exist.');
    } 

    /*
     * Function for hapus pelanggaran santri
     */
    function hapus_pelanggaran($id_pelanggaran)
    {
        // check if the pelanggaran exists before trying to edit it
        $data['pelanggaran'] = $this->Pelanggaran_pengasuhan_model->get_pelanggaran($id_pelanggaran);

        if(isset($data['pelanggaran']['id_pelanggaran']))
        {
            $this->Pelanggaran_pengasuhan_model->delete_pelanggaran($id_pelanggaran);
            $this->session->set_flashdata('hapus', 'Anda berhasil menghapus data pelanggaran <strong>' .  $data['pelanggaran']['nama_lengkap'] . '</strong>' . ' berupa <strong>' .  $data['pelanggaran']['nama_pelanggaran'] . '</strong>' );
            redirect(base_url('pengasuhan/pelanggaran/detail/' . $data['pelanggaran']['id_siswa'])) ;
        } else
        show_error('The siswa you are trying to delete does not exist.');
    }
    
    /*
     * Function for print pdf pelanggaran santri
     */
    function print()
    {
        $id_siswa = $this->input->post('id_siswa');
        $filterid = $this->input->post('print');

        if ($filterid == 1) {
            $data['datafilter'] =$this->Pelanggaran_pengasuhan_model->filter_by_id_siswa($id_siswa);
            $data['detail'] =$this->Siswa_model->detail_data($id_siswa);
        
            $data['_view'] = 'pengasuhan/pelanggaran/detail';
 
            $this->load->view('pengasuhan/pelanggaran/print_laporan', $data);
            $this->load->view('template/footer', $data);
        }
    }

    /*
     * Listing Of Input Massal
     */
    function input_massal()
    {   
        $data['siswa'] = $this->Siswa_model->get_aktif_siswa();

        $data['pelanggaranringan'] = $this->Kategori_model->get_pelanggaran_pengasuhan_ringan();
        $data['pelanggaransedang'] = $this->Kategori_model->get_pelanggaran_pengasuhan_sedang();
        $data['pelanggaranberat'] = $this->Kategori_model->get_pelanggaran_pengasuhan_berat();
        $data['penghukumpengasuhan'] = $this->Kategori_model->get_penghukum_pengasuhan();
        $data['penghukumkeamanan'] = $this->Kategori_model->get_penghukum_keamanan();

        $this->load->view('template/header',$data);
        $this->load->view('template/sidebar',$data);
        $this->load->view('pengasuhan/pelanggaran/input_massal',$data);
        $this->load->view('template/footer',$data);
    }
    
     /*
     * Function for Submit Input Massal
     */
    function simpan_massal()
    {
        $result = $this->input->post('id_siswa[]');

        $params = array();
        $nama_pelanggaran = $this->input->post('nama_pelanggaran');
        $kategori_pelanggaran = $this->input->post('kategori');
        $poin_pelanggaran = $this->input->post('poin');
        $id_penghukum = $this->input->post('penghukum');
        $keterangan = $this->input->post('keterangan');

        foreach($result as $result){
            
            $id_siswa = $result;

            array_push($params, [
                'nama_pelanggaran' => $nama_pelanggaran,
                'kategori_pelanggaran' => $kategori_pelanggaran,
                'id_penghukum' => $id_penghukum,
                'poin_pelanggaran' => $poin_pelanggaran,
                'keterangan' => $keterangan,
                'id_siswa' => $id_siswa
            ]);

        $datapoint = array(
            'poin_santri' => $poin_pelanggaran,
            );

        $jumlahdata = count($params); 
        $this->Pelanggaran_pengasuhan_model->tambah_poin_pelanggaran_massal($id_siswa, $datapoint, $poin_pelanggaran);

        $this->session->set_flashdata('berhasil', 'Anda berhasil menambahkan data pelanggaran <strong>'.$nama_pelanggaran.'</strong> sejumlah <strong>'.$jumlahdata.' Santri </strong>');
        }

        $this->db->insert_batch('record_pelanggaran_pengasuhan', $params);
        
        redirect('pengasuhan/pelanggaran/tabel_pelanggaran');
    }

    ///////////////////////////////////////////////////// GRAFIK PELANGGARAN SANTRI ////////////////////////////////////////////////////////////////

    /*
     * Listing of form Grafik Filter pelanggaran siswa
     */
    function form_filter_tanggal ()
    {
        $this->load->view('template/header');
        $this->load->view('template/sidebar');
        $this->load->view('pengasuhan/pelanggaran/form_filter_tanggal');
        $this->load->view('template/footer');
    }
   
    /*
     * Function for Submit form Grafik Filter pelanggaran siswa
     */
    function filterbytanggal()
    {
        $tanggalawal = $this->input->post('tanggalawal');
        $tanggalakhir = $this->input->post('tanggalakhir');
        $nilaitanggal = $this->input->post('nilaitanggal');

        // $data['pelanggaran'] = $this->Pelanggaran_pengasuhan_model->get_all_jenis_pelanggaran();
           
        if ($nilaitanggal == 1) {
            $data['title'] = "Data Santri yang melanggar dari tanggal '. <?php echo format_tanggal ($tanggalawal) ?> .'  hingga '. <?php echo format_tanggal ($tanggalakhir) ?>.'";
            $data['tanggalawal'] = $tanggalawal;
            $data['tanggalakhir'] = $tanggalakhir;
           
            $data['dataghosob'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_ghosob($tanggalawal,$tanggalakhir);
            $data['datatidakpakaisendal'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_tidak_pakai_sendal($tanggalawal,$tanggalakhir);
            $data['datamenjemurpakaian'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_menjemur_pakaian_di_kamar($tanggalawal,$tanggalakhir);
            $data['datatidakmenguncilemari'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_tidak_mengunci_lemari($tanggalawal,$tanggalakhir);
            $data['datatidakmemakaiperlengkapanlengkap'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_tidak_memakai_perlengkapan_lengkap($tanggalawal,$tanggalakhir);
            $data['dataterlambat'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_terlambat($tanggalawal,$tanggalakhir);
            $data['datatidakmemakaipapannama'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_tidak_memakai_papan_nama($tanggalawal,$tanggalakhir);
            $data['datasembunyidarikegiatan'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_sembunyi_dari_kegiatan($tanggalawal,$tanggalakhir);
            $data['datakaburketikamobilisasi'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_kabur_ketika_mobilisasi($tanggalawal,$tanggalakhir);
            $data['datamokel'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_mokel($tanggalawal,$tanggalakhir);
            $data['datatidakdatangpanggilan'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_tidak_datang_panggilan_bagian_lebih_dari_3_hari($tanggalawal,$tanggalakhir);
            $data['datamelanggarnormasusila'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_melanggar_norma_susila($tanggalawal,$tanggalakhir);
            $data['datamencuri'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_mencuri($tanggalawal,$tanggalakhir);
            $data['databerkelahi'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_berkelahi($tanggalawal,$tanggalakhir);
            $data['datakaburdaripondok'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_kabur_dari_pondok($tanggalawal,$tanggalakhir);
            $data['databerhubungandenganorangkampung'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_berhubungan_dengan_orang_kampung($tanggalawal,$tanggalakhir);
            $data['datamelawanpembantupimpinanpondok'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_melawan_pembantu_pimpinan_pondok($tanggalawal,$tanggalakhir);
            $data['dataterlambatkemasjid'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_terlambat_ke_masjid($tanggalawal,$tanggalakhir);
            $data['datamenyeretsandal'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal_menyeret_sandal($tanggalawal,$tanggalakhir);
          
            $this->load->view('template/header', $data);
            $this->load->view('template/sidebar', $data);
            $this->load->view('pengasuhan/pelanggaran/print_grafik', $data);
            $this->load->view('template/footer', $data);
    
        }
    }

    ///////////////////////////////////////////////////// TABEL INDEKS PELANGGARAN SANTRI ////////////////////////////////////////////////////////////////

     /*
     * Listing of tabel indeks pelanggaran siswa
     */
    function tabel_pelanggaran()
    {
        $data['pelanggaran_siswa'] = $this->Pelanggaran_pengasuhan_model->get_tabel_pelanggaran_siswa();

        $data['_view'] = 'pengasuhan/pelanggaran/tabel_indeks_pelanggaran';

        $this->load->view('template/header', $data);
        $this->load->view('template/sidebar', $data);
        $this->load->view('pengasuhan/pelanggaran/tabel_indeks_pelanggaran', $data);
        $this->load->view('template/footer', $data);
    }

    /*
     * Listing of filter pelanggaran siswa
     */
    function filter ()
    {
        $data['pelanggaranringan'] = $this->Kategori_model->get_pelanggaran_pengasuhan_ringan();
        $data['pelanggaransedang'] = $this->Kategori_model->get_pelanggaran_pengasuhan_sedang();
        $data['pelanggaranberat'] = $this->Kategori_model->get_pelanggaran_pengasuhan_berat();
        $data['penghukumpengasuhan'] = $this->Kategori_model->get_penghukum_pengasuhan();
        $data['penghukumkeamanan'] = $this->Kategori_model->get_penghukum_keamanan();
        $data['rayon'] = $this->Kategori_model->get_rayon();

        $this->load->view('template/header');
        $this->load->view('template/sidebar');
        $this->load->view('pengasuhan/filter/index_pelanggaran', $data);
        $this->load->view('template/footer');
    }


    function filterbykategoriweb($link){

    // periksa bahwa pelanggaran itu ada
    $data['pelanggaran'] = $this->Kategori_model->get_link_pelanggaran_pengasuhan($link);

    if (isset($data['pelanggaran']['link'])) {

        $data['title'] = "Data Santri Yang Melanggar Pelanggaran " . $data['pelanggaran']['nama_pelanggaran'];
        $data['datafilter'] =$this->Pelanggaran_pengasuhan_model->filter_by_pelanggaran($data['pelanggaran']['nama_pelanggaran']);

        $this->load->view('pengasuhan/filter/print_laporan', $data);
        $this->load->view('template/footer', $data);

    } else
        show_error('The Link you are trying to edit does not exist.');
    }
    
    /*
     * Function for Submit Filter Perkategori
     */
    function filterbykategori()
    {
        $nama_pelanggaran = $this->input->post('nama_pelanggaran');
        $penghukum = $this->input->post('penghukum');
        $tanggalawal = $this->input->post('tanggalawal');
        $tanggalakhir = $this->input->post('tanggalakhir');
        $rayon = $this->input->post('rayon');

        $nilaipelanggaran = $this->input->post('nilaipelanggaran');
        $nilaipenghukum = $this->input->post('nilaipenghukum');
        $nilaitanggal = $this->input->post('nilaitanggal');
        $nilairayon = $this->input->post('nilairayon');

        
    
        if ($nilaipelanggaran == 1) {
            $data['title'] = "Data Santri Yang Melanggar Pelanggaran $nama_pelanggaran";
            $data['datafilter'] =$this->Pelanggaran_pengasuhan_model->filter_by_pelanggaran($nama_pelanggaran);

            $this->load->view('pengasuhan/filter/print_laporan', $data);
            $this->load->view('template/footer', $data);
    
        }

        if ($nilaipenghukum == 1) {
            $data['title'] = "Data Santri Yang Mendapat Hukuman Oleh $penghukum";
            $data['datafilter'] =$this->Pelanggaran_pengasuhan_model->filter_by_penghukum($penghukum);
    
            $this->load->view('pengasuhan/filter/print_laporan', $data);
            $this->load->view('template/footer', $data);
    
        }

        if ($nilaitanggal == 1) {
            $data['title'] = "Data Santri Yang Melanggar Dari $tanggalawal Sampai $tanggalakhir" ;
            $data['datafilter'] =$this->Pelanggaran_pengasuhan_model->filter_by_tanggal($tanggalawal,$tanggalakhir);
    
            $this->load->view('pengasuhan/filter/print_laporan', $data);
            $this->load->view('template/footer', $data);
    
        }

        if ($nilairayon == 1) {
            $data['title'] = "Data Santri Yang Melanggar Dari Rayon $rayon";
            $data['datafilter'] =$this->Pelanggaran_pengasuhan_model->filterpelanggaran_by_rayon($rayon);
    
            $this->load->view('pengasuhan/filter/print_laporan', $data);
            $this->load->view('template/footer', $data);
    
        }
    }

    ///////////////////////////////////////////////////// POIN PELANGGARAN SANTRI ////////////////////////////////////////////////////////////////

    /*
     * Listing of tabel rekap poin santri
     */
    function tabel_rekap_point()
    {
        $data['pelanggaran_siswa'] = $this->Pelanggaran_pengasuhan_model->get_nama_distinct();

        $data['_view'] = 'pengasuhan/pelanggaran/tabel_rekap_poin';

        $this->load->view('template/header', $data);
        $this->load->view('template/sidebar', $data);
        $this->load->view('pengasuhan/pelanggaran/tabel_rekap_poin', $data);
        $this->load->view('template/footer', $data);
    }

    /*
     * Function for Hapus Dosa santri 20 poin
     */
    function hapus_point_siswa_20($id_siswa)
    {
        // periksa bahwa data santri itu ada
        $data['siswa'] = $this->Siswa_model->get_siswa($id_siswa);

        if(isset($data['siswa']['id']))
        {
            $this->Pelanggaran_pengasuhan_model->delete_point_pelanggaran_20($id_siswa);
            $this->session->set_flashdata('hapus', 'Anda berhasil menghapus point pelanggaran <strong>' .  $data['siswa']['nama_lengkap'] . '</strong>' .' Sejumlah '. '<strong>' . '20 Poin' . '</strong>');
            redirect(base_url('pengasuhan/pelanggaran/tabel_rekap_point/')) ;
        } else
        show_error('The siswa you are trying to delete does not exist.');
    }

    /*
     * Function for Hapus Dosa santri 25 poin
     */
    function hapus_point_siswa_25($id_siswa)
    {
        // periksa bahwa data santri itu ada
        $data['siswa'] = $this->Siswa_model->get_siswa($id_siswa);

        if(isset($data['siswa']['id']))
        {
            $this->Pelanggaran_pengasuhan_model->delete_point_pelanggaran_25($id_siswa);
            $this->session->set_flashdata('hapus', 'Anda berhasil menghapus point pelanggaran <strong>' .  $data['siswa']['nama_lengkap'] . '</strong>' .' Sejumlah '. '<strong>' . '25 Poin' . '</strong>');
            redirect(base_url('pengasuhan/pelanggaran/tabel_rekap_point/')) ;
        } else
        show_error('The siswa you are trying to delete does not exist.');
    }

    //////////////////////////////////////////////////// FUNGSI UNTUK TABEL PELANGGARAN ////////////////////////////////////////////////////////////////

    /*
     * Function for edit pelanggaran santri dari tabel indeks
     */
    function edit_pelanggaran_tabel($id_pelanggaran)
    {   
        // check if the pelanggaran exists before trying to edit it
        $data['pelanggaran'] = $this->Pelanggaran_pengasuhan_model->get_pelanggaran($id_pelanggaran);

        if(isset($data['pelanggaran']['id_pelanggaran']))
        {
            $this->load->library('form_validation');
			$this->form_validation->set_rules('penghukum','Penghukum','required');

            $id_pelanggaran = $data['pelanggaran']['id_pelanggaran'];
            $id_siswa = $data['pelanggaran']['id_siswa'];
            $data['detail'] = $this->Siswa_model->detail_data($id_siswa);
		
			if($this->form_validation->run())     
            {   
                $params = array(
                    'id_penghukum' => $this->input->post('penghukum'),
                    'nama_pelanggaran' => $this->input->post('nama_pelanggaran'),
                    'kategori_pelanggaran' => $this->input->post('kategori'),
                    'poin_pelanggaran' => $this->input->post('poin'),
                    'keterangan' => $this->input->post('keterangan'),
                );

                $nama_siswa = $this->input->post('nama_lengkap');

                $this->Pelanggaran_pengasuhan_model->update_pelanggaran($id_pelanggaran,$params);
                $this->session->set_flashdata('berhasil', 'Anda berhasil mengubah data hukuman pelanggaran <strong>' . $nama_siswa . '</strong>' . ' menjadi <strong>' . $this->input->post('nama_pelanggaran') . '</strong>');

                redirect(base_url('pengasuhan/pelanggaran/tabel_pelanggaran')) ;
            }
            else
            {
                $data['pelanggaranringan'] = $this->Kategori_model->get_pelanggaran_pengasuhan_ringan();
                $data['pelanggaransedang'] = $this->Kategori_model->get_pelanggaran_pengasuhan_sedang();
                $data['pelanggaranberat'] = $this->Kategori_model->get_pelanggaran_pengasuhan_berat();
                $data['penghukumpengasuhan'] = $this->Kategori_model->get_penghukum_pengasuhan();
                $data['penghukumkeamanan'] = $this->Kategori_model->get_penghukum_keamanan();

                $data['_view'] = 'pengasuhan/pelanggaran/edit_pelanggaran_tabel';
                $this->load->view('template/header',$data);
                $this->load->view('template/sidebar',$data);
                $this->load->view('pengasuhan/pelanggaran/edit_pelanggaran_tabel',$data);
                $this->load->view('template/footer',$data);
            }
        }
        else
            show_error('The Pelanggaran Santri you are trying to edit does not exist.');
    } 

    /*
     * Function of hapus pelanggaran santri dari tabel indeks
     */
    function hapus_pelanggaran_tabel($id_pelanggaran)
    {
        // check if the pelanggaran exists before trying to edit it
        $data['pelanggaran'] = $this->Pelanggaran_pengasuhan_model->get_pelanggaran($id_pelanggaran);

        if(isset($data['pelanggaran']['id_pelanggaran']))
        {
            $this->Pelanggaran_pengasuhan_model->delete_pelanggaran($id_pelanggaran);
            $this->session->set_flashdata('hapus', 'Anda berhasil menghapus data pelanggaran <strong>' .  $data['pelanggaran']['nama_lengkap'] . '</strong>' . ' berupa <strong>' .  $data['pelanggaran']['nama_pelanggaran'] . '</strong>' );
            redirect(base_url('pengasuhan/pelanggaran/tabel_pelanggaran')) ;
        } else
        show_error('The siswa you are trying to delete does not exist.');
    }


    //////////////////////////////////////////////////// FUNGSI UNTUK TABEL KATEGORI PELANGGARAN ////////////////////////////////////////////////////////////////

    /*
     * Function for tambah jenis pelanggaran santri
     */
    function tambah_kategori_pelanggaran()
    {
        // ambil data santri aktif
        $data['pelanggaran'] = $this->Pelanggaran_pengasuhan_model->get_all_kategori_pelanggaran();

        $this->load->library('form_validation');
        $this->form_validation->set_rules('nama_pelanggaran','Nama Pelanggaran','required');

        if($this->form_validation->run()) {
            
            $nama_pelanggaran = $this->input->post('nama_pelanggaran');
            $poin_pelanggaran = $this->input->post('poin_pelanggaran');
            $kategori_pelanggaran = $this->input->post('kategori');
    
            $data = array(
                'nama_pelanggaran' => $nama_pelanggaran,
                'poin' => $poin_pelanggaran,
                'kategori' => $kategori_pelanggaran,);
                
            $this->Pelanggaran_pengasuhan_model->tambah_kategori_pelanggaran($data);
            $this->session->set_flashdata('berhasil', 'Anda berhasil menambahkan data pelanggaran <strong>' . $nama_pelanggaran . ' ('. $poin_pelanggaran . ' Poin)' . '</strong>' . ' dengan kategori <strong>' . $kategori_pelanggaran . '</strong>' );
            redirect('pengasuhan/pelanggaran/tambah_kategori_pelanggaran');
        }
        else
        {
            $data['_view'] = 'pengasuhan/pelanggaran/tambah_kategori_pelanggaran';
            $this->load->view('template/header');
            $this->load->view('template/sidebar');
            $this->load->view('pengasuhan/pelanggaran/tambah_kategori_pelanggaran', $data);
            $this->load->view('template/footer');
        }
    }

    /*
     * Function for edit jenis pelanggaran santri
     */
    function edit_kategori_pelanggaran($id_kategori)
    {   
        // check if the pelanggaran exists before trying to edit it
        $data['kategori_pelanggaran'] = $this->Pelanggaran_pengasuhan_model->get_kategori_pelanggaran($id_kategori);

        if(isset($data['kategori_pelanggaran']['id']))
        {
            $this->load->library('form_validation');
            $this->form_validation->set_rules('nama_pelanggaran','Nama Pelanggaran','required');


            $id_kategori = $data['kategori_pelanggaran']['id'];
          
			if($this->form_validation->run())     
            {   
                $nama_pelanggaran = $this->input->post('nama_pelanggaran');
                $poin_pelanggaran = $this->input->post('poin_pelanggaran');
                $kategori_pelanggaran = $this->input->post('kategori');

                $data = array(
                    'nama_pelanggaran' => $nama_pelanggaran,
                    'poin' => $poin_pelanggaran,
                    'kategori' => $kategori_pelanggaran,);

                $this->Pelanggaran_pengasuhan_model->update_kategori_pelanggaran($id_kategori,$data);
                $this->session->set_flashdata('berhasil', 'Anda berhasil mengubah data pelanggaran <strong>' . $nama_pelanggaran . ' ('. $poin_pelanggaran . ' Poin)' . '</strong>' . ' dengan kategori <strong>' . $kategori_pelanggaran . '</strong>' );

                redirect(base_url('pengasuhan/pelanggaran/tambah_kategori_pelanggaran')) ;
            }
            else
            {
                
                $data['_view'] = 'pengasuhan/pelanggaran/edit_kategori_pelanggaran';
                $this->load->view('template/header',$data);
                $this->load->view('template/sidebar',$data);
                $this->load->view('pengasuhan/pelanggaran/edit_kategori_pelanggaran',$data);
                $this->load->view('template/footer',$data);
            }
        }
        else
            show_error('The Kategori Pelanggaran Santri you are trying to edit does not exist.');
    }

    /*
     * Function of hapus jenis pelanggaran santri
     */
    function hapus_kategori_pelanggaran($id_kategori)
    {
        // check if the pelanggaran exists before trying to edit it
        $data['kategori_pelanggaran'] = $this->Pelanggaran_pengasuhan_model->get_kategori_pelanggaran($id_kategori);

        if(isset($data['kategori_pelanggaran']['id']))
        {
            $this->Pelanggaran_pengasuhan_model->delete_kategori_pelanggaran($id_kategori);
            $this->session->set_flashdata('hapus', 'Anda berhasil menghapus data pelanggaran <strong>' . $data['kategori_pelanggaran']['nama_pelanggaran'] . ' ('. $data['kategori_pelanggaran']['poin'] . ' Poin)' . '</strong>' . ' dengan kategori <strong>' . $data['kategori_pelanggaran']['kategori'] . '</strong>' );
            redirect(base_url('pengasuhan/pelanggaran/tambah_kategori_pelanggaran')) ;
        } else
        show_error('The kategori pelanggaran you are trying to delete does not exist.');
    }

    //////////////////////////////////////////////////// JAVASCRIPT ////////////////////////////////////////////////////////////////

    /*
     * Javasript autofill Kategori Pelanggaran
     */
    function fill_kategori_pelanggaran(){
        $nama_pelanggaran = $_POST['nama_pelanggaran'];
        $s = "SELECT * FROM tb_pelanggaran_pengasuhan WHERE nama_pelanggaran='$nama_pelanggaran'";

        $res = $this->db->query($s)->row_array();
        echo json_encode($res);
    }
}
