<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kategori_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    ////////////////////////////////////////////////////////////////// KATEGORI SISWA /////////////////////////////////////////////////////////////////////////////
    function getkategori()
    {
        $query = $this->db->query("SELECT (kategori) AS kategori FROM tb_kategori GROUP BY (kategori) ORDER BY (kategori) ASC");
        return $query->result();
    }

    function get_kelas()
    {
        $query = $this->db->query("SELECT (kelas) AS kelas FROM tb_kelas GROUP BY (kelas) ORDER BY (kelas) ASC");
        return $query->result();
    }

    function get_rayon()
    {
        $query = $this->db->query("SELECT (rayon) AS rayon FROM tb_rayon GROUP BY (rayon) ORDER BY (rayon) ASC");
        return $query->result();
    }

    function get_provinsi()
    {
        $query = $this->db->query("SELECT DISTINCT provinsi FROM tb_kategori_alamat GROUP BY (provinsi) ORDER BY (provinsi) ASC");
        return $query->result();
    }

    function get_kabupaten()
    {
        $query = $this->db->query("SELECT DISTINCT (kabupaten) AS kabupaten FROM tb_kategori_alamat GROUP BY (kabupaten) ORDER BY (kabupaten) ASC");
        return $query->result();
    }

    ////////////////////////////////////////////////////////////////// KATEGORI PENGASUHAN /////////////////////////////////////////////////////////////////////////////

    function get_pelanggaran_pengasuhan()
    {
        $query = $this->db->query("SELECT (nama_pelanggaran) AS nama_pelanggaran FROM tb_pelanggaran_pengasuhan GROUP BY (nama_pelanggaran) ORDER BY (nama_pelanggaran) ASC");
        return $query->result();
    }

    function get_link_pelanggaran_pengasuhan($link)
    {
        return $this->db->get_where('tb_pelanggaran_pengasuhan',array('link'=>$link))->row_array();
    }

    function get_pelanggaran_pengasuhan_ringan()
    {
        $query = $this->db->query("SELECT * FROM tb_pelanggaran_pengasuhan WHERE (kategori) = 'Ringan'");
        return $query->result();
    }

    function get_pelanggaran_pengasuhan_sedang()
    {
        $query = $this->db->query("SELECT * FROM tb_pelanggaran_pengasuhan WHERE (kategori) = 'sedang' ORDER BY kategori ASC");
        return $query->result();
    }

    function get_pelanggaran_pengasuhan_berat()
    {
        $query = $this->db->query("SELECT * FROM tb_pelanggaran_pengasuhan WHERE (kategori) = 'berat' ORDER BY kategori ASC");
        return $query->result();
    }

    function get_penghukum_pengasuhan()
    {
        $query = $this->db->query("SELECT * FROM tb_staf_pengasuhan WHERE (bagian) = 'Pengasuhan Santri' ORDER BY bagian ASC");
        return $query->result();
    }

    function get_penghukum_keamanan()
    {
        $query = $this->db->query("SELECT * FROM tb_staf_pengasuhan WHERE (bagian) = 'Keamanan Pusat' ORDER BY bagian ASC");
        return $query->result();
    }

    function get_penghukum_pengurus_rayon()
    {
        $query = $this->db->query("SELECT * FROM tb_staf_pengasuhan WHERE (bagian) = 'Pengurus Rayon' ORDER BY bagian ASC");
        return $query->result();
    }

    ////////////////////////////////////////////////////////////////// KATEGORI BAKES /////////////////////////////////////////////////////////////////////////////

    function get_staf_bakes()
    {
        $query = $this->db->query("SELECT * FROM tb_staf_bakes WHERE (bagian) = 'Bagian Kesehatan' ORDER BY bagian ASC");
        return $query->result();
    }

    function get_staf_bakes_kelas6()
    {
        $query = $this->db->query("SELECT * FROM tb_staf_bakes WHERE (bagian) = 'Kelas 6' ORDER BY bagian ASC");
        return $query->result();
    }

    function get_penyakit_biasa()
    {
        $query = $this->db->query("SELECT * FROM tb_jenis_penyakit WHERE (kategori) = 'Biasa' ORDER BY kategori ASC");
        return $query->result();
    }

    function get_penyakit_sedang()
    {
        $query = $this->db->query("SELECT * FROM tb_jenis_penyakit WHERE (kategori) = 'Sedang' ORDER BY kategori ASC");
        return $query->result();
    }

    function get_penyakit_menular()
    {
        $query = $this->db->query("SELECT * FROM tb_jenis_penyakit WHERE (kategori) = 'Menular' ORDER BY kategori ASC");
        return $query->result();
    }

    ////////////////////////////////////////////////////////////////// KATEGORI PERIZINAN /////////////////////////////////////////////////////////////////////////////

    function get_tujuan_jauh()
    {
        $query = $this->db->query("SELECT * FROM tb_tujuan_perizinan WHERE (kategori) = 'Jauh' ORDER BY kategori ASC");
        return $query->result();
    }

    function get_tujuan_dekat()
    {
        $query = $this->db->query("SELECT * FROM tb_tujuan_perizinan WHERE (kategori) = 'dekat' ORDER BY kategori ASC");
        return $query->result();
    }

    ////////////////////////////////////////////////////////////////// KATEGORI KMI /////////////////////////////////////////////////////////////////////////////

    function get_pelanggaran_kmi_ringan()
    {
        $query = $this->db->query("SELECT * FROM tb_pelanggaran_kmi WHERE (kategori) = 'Ringan'");
        return $query->result();
    }

    function get_pelanggaran_kmi_sedang()
    {
        $query = $this->db->query("SELECT * FROM tb_pelanggaran_kmi WHERE (kategori) = 'Sedang' ORDER BY kategori ASC");
        return $query->result();
    }

    function get_pelanggaran_kmi_berat()
    {
        $query = $this->db->query("SELECT * FROM tb_pelanggaran_kmi WHERE (kategori) = 'Berat' ORDER BY kategori ASC");
        return $query->result();
    }

    function get_staf_kmi()
    {
        $query = $this->db->query("SELECT * FROM tb_staf_kmi WHERE (bagian) = 'Staf KMI' ORDER BY bagian ASC");
        return $query->result();
    }

    function get_perizinan_piket()
    {
        $query = $this->db->query("SELECT * FROM tb_perizinan_kmi WHERE (jenis_perizinan) = 'Piket'");
        return $query->result();
    }

    function get_perizinan_panitia()
    {
        $query = $this->db->query("SELECT * FROM tb_perizinan_kmi WHERE (jenis_perizinan) = 'Panitia'");
        return $query->result();
    }

    function get_perizinan_sakit()
    {
        $query = $this->db->query("SELECT * FROM tb_perizinan_kmi WHERE (jenis_perizinan) = 'Sakit'");
        return $query->result();
    }

    function get_perizinan_lainlain()
    {
        $query = $this->db->query("SELECT * FROM tb_perizinan_kmi WHERE (jenis_perizinan) = 'Lain-lain'");
        return $query->result();
    }

    ////////////////////////////////////////////////////////////////// KATEGORI BAHASA /////////////////////////////////////////////////////////////////////////////

    function get_pelanggaran_bahasa_ringan()
    {
        $query = $this->db->query("SELECT * FROM tb_pelanggaran_bahasa WHERE (kategori) = 'Ringan' ORDER BY kategori ASC");
        return $query->result();
    }

    function get_pelanggaran_bahasa_sedang()
    {
        $query = $this->db->query("SELECT * FROM tb_pelanggaran_bahasa WHERE (kategori) = 'Sedang' ORDER BY kategori ASC");
        return $query->result();
    }

    function get_pelanggaran_bahasa_berat()
    {
        $query = $this->db->query("SELECT * FROM tb_pelanggaran_bahasa WHERE (kategori) = 'Berat' ORDER BY kategori ASC");
        return $query->result();
    }

    function get_staf_LAC()
    {
        $query = $this->db->query("SELECT * FROM tb_staf_bahasa WHERE (bagian) = 'LAC' ORDER BY id ASC");
        return $query->result();
    }

    function get_staf_CLI()
    {
        $query = $this->db->query("SELECT * FROM tb_staf_bahasa WHERE (bagian) = 'CLI' ORDER BY bagian ASC");
        return $query->result();
    }

     ////////////////////////////////////////////////////////////////// KATEGORI pusdac /////////////////////////////////////////////////////////////////////////////

     function get_pelanggaran_pusdac_ringan()
     {
         $query = $this->db->query("SELECT * FROM tb_pelanggaran_pusdac WHERE (kategori) = 'Ringan' ORDER BY id ASC");
         return $query->result();
     }
 
     function get_pelanggaran_pusdac_sedang()
     {
         $query = $this->db->query("SELECT * FROM tb_pelanggaran_pusdac WHERE (kategori) = 'Sedang' ORDER BY id ASC");
         return $query->result();
     }
 
     function get_pelanggaran_pusdac_berat()
     {
         $query = $this->db->query("SELECT * FROM tb_pelanggaran_pusdac WHERE (kategori) = 'Berat' ORDER BY id ASC");
         return $query->result();
     }
 
     function get_staf_pusdac()
     {
         $query = $this->db->query("SELECT * FROM tb_staf_pusdac WHERE (bagian) = 'PUSDAC' ORDER BY id ASC");
         return $query->result();
     }
 
     function get_staf_talim()
     {
         $query = $this->db->query("SELECT * FROM tb_staf_pusdac WHERE (bagian) = 'Kelas 6' ORDER BY bagian ASC");
         return $query->result();
     }

}