<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pelanggaran_kmi_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    

    /*
     * function to tambah pelanggaran siswa
     */
    function tambah_pelanggaran($data){
        $this->db->insert('record_pelanggaran_kmi', $data);
    }

     /*
     * function to update pelanggaran
     */
    function update_pelanggaran($id_pelanggaran,$params)
    {
        $this->db->where('id',$id_pelanggaran);
        return $this->db->update('record_pelanggaran_kmi',$params);
    }

    /*
     * function to delete pelanggaran siswa
     */
    function delete_pelanggaran($id_pelanggaran)
    {
        $this->db->select('*, record_pelanggaran_kmi.id as id_pelanggaran, siswa.id as id_siswa ');
        $this->db->from('record_pelanggaran_kmi');
        $this->db->join('siswa','siswa.id = record_pelanggaran_kmi.id_siswa');
        $this->db->where('record_pelanggaran_kmi.id', $id_pelanggaran);
        return $this->db->delete('record_pelanggaran_kmi',array('id'=>$id_pelanggaran));
    }

    /*
     * Get pelanggaran by id pelanggaran
     */
    function get_pelanggaran($id)
    {
        $this->db->select('*, record_pelanggaran_kmi.id as id_pelanggaran, siswa.id as id_siswa ');
        $this->db->from('record_pelanggaran_kmi');
        $this->db->join('siswa','siswa.id = record_pelanggaran_kmi.id_siswa');
        $this->db->join('tb_staf_kmi','tb_staf_kmi.id = record_pelanggaran_kmi.id_penghukum');
        $this->db->where('record_pelanggaran_kmi.id', $id);
        $this->db->order_by('nama_lengkap', 'desc');
        return $this->db->get()->row_array();

        // return $this->db->get_where('record_pelanggaran_kmi',array('id'=>$id))->row_array();
    }
    
    /*
     * function to view detail pelanggaran siswa
     */
    function filter_by_id_siswa($id)
    {
        $this->db->select('*, record_pelanggaran_kmi.id as id_pelanggaran, siswa.id as id_siswa ');
        $this->db->from('record_pelanggaran_kmi');
        $this->db->join('siswa','siswa.id = record_pelanggaran_kmi.id_siswa');
        $this->db->join('tb_staf_kmi','tb_staf_kmi.id = record_pelanggaran_kmi.id_penghukum');
        $this->db->where('id_siswa', $id);
        $this->db->order_by('create_at', 'desc');
        return $this->db->get()->result();
    }

    /*
     * function to get tabel newest pelanggaran siswa
     */
    function get_tabel_pelanggaran_siswa()
    {
        $this->db->select('*, record_pelanggaran_kmi.id as id_pelanggaran, siswa.id as id_siswa ');
        $this->db->from('record_pelanggaran_kmi');
        $this->db->join('siswa','siswa.id = record_pelanggaran_kmi.id_siswa');
        $this->db->join('tb_staf_kmi','tb_staf_kmi.id = record_pelanggaran_kmi.id_penghukum');
        $this->db->order_by('create_at', 'desc');
        $this->db->order_by('siswa.id', 'asc');
        return $this->db->get()->result_array();
    }

    /////////////////////////////////////////////////////filter data pelanggaran perkategori////////////////////////////////////////////////////////////////

    function filter_by_pelanggaran($nama_pelanggaran)
    {
        $this->db->select('*');
        $this->db->from('record_pelanggaran_kmi');
        $this->db->join('siswa','siswa.id = record_pelanggaran_kmi.id_siswa');
        $this->db->join('tb_staf_kmi','tb_staf_kmi.id = record_pelanggaran_kmi.id_penghukum');
        $this->db->where('nama_pelanggaran', $nama_pelanggaran);
        $this->db->order_by('create_at', 'desc');
        $this->db->order_by('siswa.id', 'asc');
        return $this->db->get()->result();
    }

    function filter_by_penghukum($penghukum)
    {
        $this->db->select('*');
        $this->db->from('record_pelanggaran_kmi');
        $this->db->join('siswa','siswa.id = record_pelanggaran_kmi.id_siswa');
        $this->db->join('tb_staf_kmi','tb_staf_kmi.id = record_pelanggaran_kmi.id_penghukum');
        $this->db->where('nama', $penghukum);
        $this->db->order_by('create_at', 'desc');
        $this->db->order_by('siswa.id', 'asc');
        // $this->db->where('rayon', "Syanggit Lt. 1");
        return $this->db->get()->result();
    }

    function filter_by_tanggal($tanggalawal,$tanggalakhir)
    {
        $this->db->select('*');
        $this->db->from('record_pelanggaran_kmi');
        $this->db->join('siswa','siswa.id = record_pelanggaran_kmi.id_siswa');
        $this->db->join('tb_staf_kmi','tb_staf_kmi.id = record_pelanggaran_kmi.id_penghukum');
        $this->db->where("(create_at) BETWEEN '$tanggalawal' AND '$tanggalakhir'");
        $this->db->order_by('create_at', 'desc');
        $this->db->order_by('siswa.id', 'asc');
        return $this->db->get()->result();
    }

    function filterpelanggaran_by_rayon($rayon)
    {
        $this->db->select('*');
        $this->db->from('record_pelanggaran_kmi');
        $this->db->join('siswa','siswa.id = record_pelanggaran_kmi.id_siswa');
        $this->db->join('tb_staf_kmi','tb_staf_kmi.id = record_pelanggaran_kmi.id_penghukum');
        $this->db->where('siswa.rayon', "$rayon");
        $this->db->order_by('create_at', 'desc');
        $this->db->order_by('siswa.id', 'asc');
        return $this->db->get()->result();
    }

    ////////////////////////////////////////////////////hitungan grafik pelanggaran perkategori////////////////////////////////////////////////////////////////

    /*
     * Get all kategori Pelanggaran
     */
    function get_all_kategori_pelanggaran()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('tb_pelanggaran_pengasuhan')->result_array();
    }

     /*
     * Get kategori pelanggaran by id 
     */
    function get_kategori_pelanggaran($id)
    {
        $this->db->select('*');
        $this->db->from('tb_pelanggaran_pengasuhan');
        $this->db->where('tb_pelanggaran_pengasuhan.id', $id);
        $this->db->order_by('id', 'desc');
        return $this->db->get()->row_array();
    }

     /*
     * function to tambah pelanggaran siswa
     */
    function tambah_kategori_pelanggaran($data)
    {
        $this->db->insert('tb_pelanggaran_pengasuhan', $data);
    }
    
     /*
     * function to update pelanggaran
     */
    function update_kategori_pelanggaran($id_kategori,$data)
    {
        $this->db->where('id',$id_kategori);
        return $this->db->update('tb_pelanggaran_pengasuhan',$data);
    }

    /*
     * function to delete pelanggaran siswa
     */
    function delete_kategori_pelanggaran($id_kategori)
    {
        $this->db->select('*');
        $this->db->from('tb_pelanggaran_pengasuhan');
        $this->db->where('tb_pelanggaran_pengasuhan.id', $id_kategori);
        return $this->db->delete('tb_pelanggaran_pengasuhan',array('id'=>$id_kategori));
    }

    ////////////////////////////////////////////////////hitungan grafik pelanggaran perkategori////////////////////////////////////////////////////////////////

   
    /*
     * function to menghitung data Terlambat
     */
    function filter_by_tanggal_terlambat($tanggalawal,$tanggalakhir)
    {
        $query = $this->db->query("SELECT * FROM record_pelanggaran_kmi WHERE create_at BETWEEN '$tanggalawal' AND '$tanggalakhir' HAVING nama_pelanggaran = 'Terlambat'");
        return $query->num_rows();
    }

    /*
     * function to menghitung data Tidak Piket Kelas
     */
    function filter_by_tanggal_tidak_piket_kelas($tanggalawal,$tanggalakhir)
    {
        $query = $this->db->query("SELECT * FROM record_pelanggaran_kmi WHERE create_at BETWEEN '$tanggalawal' AND '$tanggalakhir' HAVING nama_pelanggaran = 'Tidak Piket Kelas'");
        return $query->num_rows();
    }

    /*
     * function to menghitung data Keluar Kelas Ketika Jam Pelajaran Berlangsung
     */
    function filter_by_tanggal_keluar_kelas($tanggalawal,$tanggalakhir)
    {
        $query = $this->db->query("SELECT * FROM record_pelanggaran_kmi WHERE create_at BETWEEN '$tanggalawal' AND '$tanggalakhir' HAVING nama_pelanggaran = 'Keluar Kelas Ketika Jam Pelajaran Berlangsung'");
        return $query->num_rows();
    }

    /*
     * function to menghitung data Tidak Mengenakan Kaos Kaki
     */
    function filter_by_tanggal_tidak_pakai_kaos_kaki($tanggalawal,$tanggalakhir)
    {
        $query = $this->db->query("SELECT * FROM record_pelanggaran_kmi WHERE create_at BETWEEN '$tanggalawal' AND '$tanggalakhir' HAVING nama_pelanggaran = 'Tidak Mengenakan Kaos Kaki'");
        return $query->num_rows();
    }

    /*
     * function to menghitung data Tidak Mengikuti Muajjah
     */
    function filter_by_tanggal_tidak_muajjah($tanggalawal,$tanggalakhir)
    {
        $query = $this->db->query("SELECT * FROM record_pelanggaran_kmi WHERE create_at BETWEEN '$tanggalawal' AND '$tanggalakhir' HAVING nama_pelanggaran = 'Tidak Mengikuti Muajjah'");
        return $query->num_rows();
    }

    /*
     * function to menghitung data Tidak Izin Memakai Sendal
     */
    function filter_by_tanggal_tidak_izin_pakai_sendal($tanggalawal,$tanggalakhir)
    {
        $query = $this->db->query("SELECT * FROM record_pelanggaran_kmi WHERE create_at BETWEEN '$tanggalawal' AND '$tanggalakhir' HAVING nama_pelanggaran = 'Tidak Izin Memakai Sendal'");
        return $query->num_rows();
    }

    /*
     * function to menghitung data Tidak Membawa Tas Sepatu
     */
    function filter_by_tanggal_tidak_membawa_tassepatu($tanggalawal,$tanggalakhir)
    {
        $query = $this->db->query("SELECT * FROM record_pelanggaran_kmi WHERE create_at BETWEEN '$tanggalawal' AND '$tanggalakhir' HAVING nama_pelanggaran = 'Tidak Membawa Tas Sepatu'");
        return $query->num_rows();
    }

    /*
     * function to menghitung data Tidak Mengumpulkan Insya Usbu'i
     */
    function filter_by_tanggal_tidak_mengumpulkan_insya($tanggalawal,$tanggalakhir)
    {
        $query = $this->db->query("SELECT * FROM record_pelanggaran_kmi WHERE create_at BETWEEN '$tanggalawal' AND '$tanggalakhir' HAVING nama_pelanggaran = 'Tidak Mengumpulkan Insya Usbui'");
        return $query->num_rows();
    }

    /*
     * function to menghitung data Membawa Barang Terlarang
     */
    function filter_by_tanggal_membawa_barang_terlarang($tanggalawal,$tanggalakhir)
    {
        $query = $this->db->query("SELECT * FROM record_pelanggaran_kmi WHERE create_at BETWEEN '$tanggalawal' AND '$tanggalakhir' HAVING nama_pelanggaran = 'Membawa Barang Terlarang'");
        return $query->num_rows();
    }

    /*
     * function to menghitung data Menerlambatkan Diri
     */
    function filter_by_tanggal_menerlambatkan_diri($tanggalawal,$tanggalakhir)
    {
        $query = $this->db->query("SELECT * FROM record_pelanggaran_kmi WHERE create_at BETWEEN '$tanggalawal' AND '$tanggalakhir' HAVING nama_pelanggaran = 'Menerlambatkan Diri'");
        return $query->num_rows();
    }

    /*
     * function to menghitung data Ghoib Kelas
     */
    function filter_by_tanggal_ghoib_kelas($tanggalawal,$tanggalakhir)
    {
        $query = $this->db->query("SELECT * FROM record_pelanggaran_kmi WHERE create_at BETWEEN '$tanggalawal' AND '$tanggalakhir' HAVING nama_pelanggaran = 'Ghoib Kelas'");
        return $query->num_rows();
    }

}