<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pelanggaran_pusdac_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    ///////////////////////////////////////////////////// PELANGGARAN SANTRI ////////////////////////////////////////////////////////////////

    /*
     * function to tambah pelanggaran santri
     */
    function tambah_pelanggaran($data){
        $this->db->insert('record_pelanggaran_pusdac', $data);
    }

     /*
     * function to update pelanggaran santri
     */
    function update_pelanggaran($id_pelanggaran,$params)
    {
        $this->db->where('id',$id_pelanggaran);
        return $this->db->update('record_pelanggaran_pusdac',$params);
    }

    /*
     * function to delete pelanggaran santri
     */
    function delete_pelanggaran($id_pelanggaran)
    {
        $this->db->select('*, record_pelanggaran_pusdac.id as id_pelanggaran, siswa.id as id_siswa ');
        $this->db->from('record_pelanggaran_pusdac');
        $this->db->join('siswa','siswa.id = record_pelanggaran_pusdac.id_siswa');
        $this->db->where('record_pelanggaran_pusdac.id', $id_pelanggaran);
        return $this->db->delete('record_pelanggaran_pusdac',array('id'=>$id_pelanggaran));
    }

    /*
     * function to get pelanggaran by id pelanggaran
     */
    function get_pelanggaran($id)
    {
        $this->db->select('*, record_pelanggaran_pusdac.id as id_pelanggaran, siswa.id as id_siswa ');
        $this->db->from('record_pelanggaran_pusdac');
        $this->db->join('siswa','siswa.id = record_pelanggaran_pusdac.id_siswa');
        $this->db->join('tb_staf_bahasa','tb_staf_bahasa.id = record_pelanggaran_pusdac.id_penghukum');
        $this->db->where('record_pelanggaran_pusdac.id', $id);
        $this->db->order_by('nama_lengkap', 'desc');
        return $this->db->get()->row_array();
    }
    
    /*
     * function to view detail pelanggaran santri
     */
    function filter_by_id_siswa($id)
    {
        $this->db->select('*, record_pelanggaran_pusdac.id as id_pelanggaran, siswa.id as id_siswa ');
        $this->db->from('record_pelanggaran_pusdac');
        $this->db->join('siswa','siswa.id = record_pelanggaran_pusdac.id_siswa');
        $this->db->join('tb_staf_bahasa','tb_staf_bahasa.id = record_pelanggaran_pusdac.id_penghukum');
        $this->db->where('id_siswa', $id);
        $this->db->order_by('create_at', 'desc');
        return $this->db->get()->result();
    }

    /*
     * function to get tabel indeks pelanggaran santri terbaru
     */
    function get_tabel_pelanggaran_siswa()
    {
        $this->db->select('*, record_pelanggaran_pusdac.id as id_pelanggaran, siswa.id as id_siswa ');
        $this->db->from('record_pelanggaran_pusdac');
        $this->db->join('siswa','siswa.id = record_pelanggaran_pusdac.id_siswa');
        $this->db->join('tb_staf_bahasa','tb_staf_bahasa.id = record_pelanggaran_pusdac.id_penghukum');
        $this->db->order_by('create_at', 'desc');
        $this->db->order_by('siswa.id', 'asc');
        return $this->db->get()->result_array();
    }

    ///////////////////////////////////////////////////// POIN PELANGGARAN SANTRI ////////////////////////////////////////////////////////////////

    /*
     * function to tambah point pelanggaran siswa
     */
    function tambah_poin_pelanggaran($id_siswa, $datapoint, $poin_pelanggaran)
    {
        $this->db->where('id_siswa', $id_siswa);
        $q = $this->db->get('rekap_point_bahasa');
        $this->db->reset_query();
            
        if ( $q->num_rows() > 0 ) 
        {
            $this->db->query("UPDATE rekap_point_bahasa SET poin_santri = poin_santri + $poin_pelanggaran WHERE id_siswa = $id_siswa");
        } else {
            $this->db->set('id_siswa', $id_siswa)->insert('rekap_point_bahasa', $datapoint);
        }
    }

    /*
     * function to tambah point pelanggaran siswa massal
     */
    function tambah_poin_pelanggaran_massal($id_siswa, $datapoint, $poin_pelanggaran)
    {
        $this->db->where_in('id_siswa', $id_siswa);
        $q = $this->db->get('rekap_point_bahasa');
        $this->db->reset_query();
            
        if ( $q->num_rows() > 0 ) 
        {
            $this->db->query("UPDATE rekap_point_bahasa SET poin_santri = poin_santri + $poin_pelanggaran WHERE id_siswa = $id_siswa");
        } else {
            $this->db->set('id_siswa', $id_siswa)->insert('rekap_point_bahasa', $datapoint);
        }
    }

    /*
     * function to delete point pelanggaran siswa 20 poin
     */
    function delete_point_pelanggaran_20($id_siswa)
    {
        $this->db->query("UPDATE rekap_point_bahasa SET poin_santri = poin_santri - 20 WHERE id_siswa = $id_siswa");
        $this->db->query("DELETE FROM rekap_point_bahasa WHERE id_siswa = $id_siswa AND poin_santri = 0 ");
    }

    /*
     * function to delete point pelanggaran siswa 25 poin
     */
    function delete_point_pelanggaran_25($id_siswa)
    {
        $this->db->query("UPDATE rekap_point_bahasa SET poin_santri = poin_santri - 25 WHERE id_siswa = $id_siswa");
        $this->db->query("DELETE FROM rekap_point_bahasa WHERE id_siswa = $id_siswa AND poin_santri = 0 ");
    }

    /*
     * function to get tabel nama distinct
     */
    function get_nama_distinct()
    {
        $this->db->select('*, siswa.id as id_siswa ');
        $this->db->from('rekap_point_bahasa');
        $this->db->join('siswa','siswa.id = rekap_point_bahasa.id_siswa');
        $this->db->order_by('siswa.id', 'asc');
        return $this->db->get()->result_array();
    }

    ///////////////////////////////////////////////////// FILTER DATA PELANGGARAN PERKATEGORI ////////////////////////////////////////////////////////////////

    /*
     * function to filter by jenis pelanggaran
     */
    function filter_by_pelanggaran($nama_pelanggaran)
    {
        $this->db->select('*');
        $this->db->from('record_pelanggaran_pusdac');
        $this->db->join('siswa','siswa.id = record_pelanggaran_pusdac.id_siswa');
        $this->db->join('tb_staf_bahasa','tb_staf_bahasa.id = record_pelanggaran_pusdac.id_penghukum');
        $this->db->where('nama_pelanggaran', $nama_pelanggaran);
        $this->db->order_by('create_at', 'desc');
        $this->db->order_by('siswa.id', 'asc');
        return $this->db->get()->result();
    }

    /*
     * function to filter by penghukum
     */
    function filter_by_penghukum($penghukum)
    {
        $this->db->select('*');
        $this->db->from('record_pelanggaran_pusdac');
        $this->db->join('siswa','siswa.id = record_pelanggaran_pusdac.id_siswa');
        $this->db->join('tb_staf_bahasa','tb_staf_bahasa.id = record_pelanggaran_pusdac.id_penghukum');
        $this->db->where('nama', $penghukum);
        $this->db->order_by('create_at', 'desc');
        $this->db->order_by('siswa.id', 'asc');
        // $this->db->where('rayon', "Syanggit Lt. 1");
        return $this->db->get()->result();
    }

    /*
     * function to filter by tanggal
     */
    function filter_by_tanggal($tanggalawal,$tanggalakhir)
    {
        $this->db->select('*');
        $this->db->from('record_pelanggaran_pusdac');
        $this->db->join('siswa','siswa.id = record_pelanggaran_pusdac.id_siswa');
        $this->db->join('tb_staf_bahasa','tb_staf_bahasa.id = record_pelanggaran_pusdac.id_penghukum');
        $this->db->where("(create_at) BETWEEN '$tanggalawal' AND '$tanggalakhir'");
        $this->db->order_by('create_at', 'desc');
        $this->db->order_by('siswa.id', 'asc');
        return $this->db->get()->result();
    }

    /*
     * function to filter by rayon pelanggar
     */
    function filterpelanggaran_by_rayon($rayon)
    {
        $this->db->select('*');
        $this->db->from('record_pelanggaran_pusdac');
        $this->db->join('siswa','siswa.id = record_pelanggaran_pusdac.id_siswa');
        $this->db->join('tb_staf_bahasa','tb_staf_bahasa.id = record_pelanggaran_pusdac.id_penghukum');
        $this->db->where('siswa.rayon', "$rayon");
        $this->db->order_by('create_at', 'desc');
        $this->db->order_by('siswa.id', 'asc');
        return $this->db->get()->result();
    }

    //////////////////////////////////////////////////// JENIS PELANGGARAN ////////////////////////////////////////////////////////////////

    /*
     * Get all jenis Pelanggaran
     */
    function get_all_kategori_pelanggaran()
    {
        $this->db->order_by('poin', 'asc');
        return $this->db->get('tb_pelanggaran_bahasa')->result_array();
    }

    /*
     * Get jenis Pelanggaran
     */
    function get_all_jenis_pelanggaran()
    {
        $this->db->select('nama_pelanggaran');
        return $this->db->get('tb_pelanggaran_bahasa')->result_array();
    }

     /*
     * Get jenis pelanggaran by id 
     */
    function get_kategori_pelanggaran($id)
    {
        $this->db->select('*');
        $this->db->from('tb_pelanggaran_bahasa');
        $this->db->where('tb_pelanggaran_bahasa.id', $id);
        $this->db->order_by('id', 'desc');
        return $this->db->get()->row_array();
    }

     /*
     * function to tambah jenis pelanggaran siswa
     */
    function tambah_kategori_pelanggaran($data)
    {
        $this->db->insert('tb_pelanggaran_bahasa', $data);
    }
    
     /*
     * function to update jenis pelanggaran siswa
     */
    function update_kategori_pelanggaran($id_kategori,$data)
    {
        $this->db->where('id',$id_kategori);
        return $this->db->update('tb_pelanggaran_bahasa',$data);
    }

    /*
     * function to delete jenis pelanggaran siswa
     */
    function delete_kategori_pelanggaran($id_kategori)
    {
        $this->db->select('*');
        $this->db->from('tb_pelanggaran_bahasa');
        $this->db->where('tb_pelanggaran_bahasa.id', $id_kategori);
        return $this->db->delete('tb_pelanggaran_bahasa',array('id'=>$id_kategori));
    }

    //////////////////////////////////////////////////// HITUNGAN GRAFIK PELANGGARAN PERKATEGORI ////////////////////////////////////////////////////////////////

   
    /*
     * function to menghitung data bicara bahasa indo
     */
    function filter_by_tanggal_bicaraindo($tanggalawal,$tanggalakhir)
    {
        $query = $this->db->query("SELECT * FROM record_pelanggaran_pusdac WHERE create_at BETWEEN '$tanggalawal' AND '$tanggalakhir' HAVING nama_pelanggaran = 'Berbicara Bahasa Indonesia'");
        return $query->num_rows();
    }

    /*
     * function to menghitung data bicara bahasa daerah
     */
    function filter_by_tanggal_bicaradaerah($tanggalawal,$tanggalakhir)
    {
        $query = $this->db->query("SELECT * FROM record_pelanggaran_pusdac WHERE create_at BETWEEN '$tanggalawal' AND '$tanggalakhir' HAVING nama_pelanggaran = 'Berbicara Bahasa Daerah'");
        return $query->num_rows();
    }

    /*
     * function to menghitung data bicara kasar
     */
    function filter_by_tanggal_bicarakasar($tanggalawal,$tanggalakhir)
    {
        $query = $this->db->query("SELECT * FROM record_pelanggaran_pusdac WHERE create_at BETWEEN '$tanggalawal' AND '$tanggalakhir' HAVING nama_pelanggaran = 'Berbicara Perkataan Kasar'");
        return $query->num_rows();
    }

   

}