<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Perizinan_pengasuhan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * function to tambah perizinan siswa
     */
    function tambah_perizinan($data){
        $this->db->insert('record_perizinan_pengasuhan', $data);
    }

     /*
     * function to update perizinan
     */
    function update_perizinan($id_perizinan,$params)
    {
        $this->db->where('id',$id_perizinan);
        return $this->db->update('record_perizinan_pengasuhan',$params);
    }

    /*
     * function to delete perizinan siswa
     */
    function delete_perizinan($id_perizinan)
    {
        $this->db->select('*, record_perizinan_pengasuhan.id as id_perizinan, siswa.id as id_siswa ');
        $this->db->from('record_perizinan_pengasuhan');
        $this->db->join('siswa','siswa.id = record_perizinan_pengasuhan.id_siswa');
        $this->db->join('tb_tujuan_perizinan','tb_penghukum_pengasuhan.id = record_perizinan_pengasuhan.id_pengizin');
        $this->db->where('record_perizinan_pengasuhan.id', $id_perizinan);
        return $this->db->delete('record_perizinan_pengasuhan',array('id'=>$id_perizinan));
    }

    /*
     * Get perizinan by id perizinan
     */
    function get_perizinan($id)
    {
        $this->db->select('*, record_perizinan_pengasuhan.id as id_perizinan, siswa.id as id_siswa ');
        $this->db->from('record_perizinan_pengasuhan');
        $this->db->join('siswa','siswa.id = record_perizinan_pengasuhan.id_siswa');
        $this->db->join('tb_penghukum_pengasuhan','tb_penghukum_pengasuhan.id = record_perizinan_pengasuhan.id_pengizin');
        $this->db->join('tb_tujuan_perizinan','tb_penghukum_pengasuhan.id = record_perizinan_pengasuhan.id_pengizin');
        $this->db->where('record_perizinan_pengasuhan.id', $id);
        $this->db->order_by('nama_lengkap', 'desc');
        return $this->db->get()->row_array();

        // return $this->db->get_where('record_perizinan_pengasuhan',array('id'=>$id))->row_array();
    }
    
    /*
     * function to view detail perizinan siswa
     */
    function filter_by_id_siswa($id)
    {
        $this->db->select('*, record_perizinan_pengasuhan.id as id_perizinan, siswa.id as id_siswa, ');
        $this->db->from('record_perizinan_pengasuhan');
        $this->db->join('siswa','siswa.id = record_perizinan_pengasuhan.id_siswa');
        $this->db->join('tb_penghukum_pengasuhan','tb_penghukum_pengasuhan.id = record_perizinan_pengasuhan.id_pengizin');
        $this->db->where('id_siswa', $id);
        $this->db->order_by('nama_lengkap', 'desc');
        return $this->db->get()->result();
    }

    /*
     * function to get tabel newest perizinan siswa
     */
    function get_tabel_perizinan_siswa()
    {
        $this->db->select('*, record_perizinan_pengasuhan.id as id_perizinan, siswa.id as id_siswa ');
        $this->db->from('record_perizinan_pengasuhan');
        $this->db->join('siswa','siswa.id = record_perizinan_pengasuhan.id_siswa');
        $this->db->join('tb_penghukum_pengasuhan','tb_penghukum_pengasuhan.id = record_perizinan_pengasuhan.id_pengizin');
        $this->db->order_by('create_at', 'desc');
        $this->db->order_by('siswa.id', 'asc');
        return $this->db->get()->result_array();
    }

    /////////////////////////////////////////////////////hitungan grafik perizinan perkategori////////////////////////////////////////////////////////////////

    function filter_by_perizinan($nama_perizinan)
    {
        $this->db->select('*,');
        $this->db->from('record_perizinan_pengasuhan');
        $this->db->join('siswa','siswa.id = record_perizinan_pengasuhan.id_siswa');
        $this->db->join('tb_penghukum_pengasuhan','tb_penghukum_pengasuhan.id = record_perizinan_pengasuhan.id_pengizin');
        $this->db->where('nama_perizinan', $nama_perizinan);
        $this->db->order_by('create_at', 'desc');
        $this->db->order_by('siswa.id', 'asc');
        return $this->db->get()->result();
    }


    function filter_by_pengizin($pengizin)
    {
        $this->db->select('*, tb_penghukum_pengasuhan.nama_penghukum as nama_pengizin,');
        $this->db->from('record_perizinan_pengasuhan');
        $this->db->join('siswa','siswa.id = record_perizinan_pengasuhan.id_siswa');
        $this->db->join('tb_penghukum_pengasuhan','tb_penghukum_pengasuhan.id = record_perizinan_pengasuhan.id_pengizin');
        $this->db->join('tb_tujuan_perizinan','tb_penghukum_pengasuhan.id = record_perizinan_pengasuhan.id_pengizin');
        $this->db->where('tb_penghukum_pengasuhan.nama_penghukum', $pengizin);
        $this->db->order_by('create_at', 'desc');
        $this->db->order_by('siswa.id', 'asc');
        // $this->db->where('rayon', "Syanggit Lt. 1");
        return $this->db->get()->result();
    }

    function filter_by_tanggal($tanggalawal,$tanggalakhir)
    {
        $this->db->select('*,');
        $this->db->from('record_perizinan_pengasuhan');
        $this->db->join('siswa','siswa.id = record_perizinan_pengasuhan.id_siswa');
        $this->db->join('tb_penghukum_pengasuhan','tb_penghukum_pengasuhan.id = record_perizinan_pengasuhan.id_pengizin');
        $this->db->join('tb_tujuan_perizinan','tb_penghukum_pengasuhan.id = record_perizinan_pengasuhan.id_pengizin');
        $this->db->where("(create_at) BETWEEN '$tanggalawal' AND '$tanggalakhir'");
        $this->db->order_by('create_at', 'desc');
        $this->db->order_by('siswa.id', 'asc');
        return $this->db->get()->result();
    }

    function filterperizinan_by_rayon($rayon)
    {
        $this->db->select('*,');
        $this->db->from('record_perizinan_pengasuhan');
        $this->db->join('siswa','siswa.id = record_perizinan_pengasuhan.id_siswa');
        $this->db->join('tb_penghukum_pengasuhan','tb_penghukum_pengasuhan.id = record_perizinan_pengasuhan.id_pengizin');
        $this->db->join('tb_tujuan_perizinan','tb_penghukum_pengasuhan.id = record_perizinan_pengasuhan.id_pengizin');
        $this->db->where('rayon', "$rayon");
        $this->db->order_by('create_at', 'desc');
        $this->db->order_by('siswa.id', 'asc');
        return $this->db->get()->result();
    }
    
    ////////////////////////////////////////////////////hitungan grafik perizinan perkategori////////////////////////////////////////////////////////////////


    /*
     * function to menghitung data kabur
     */
    function filter_by_tanggal_sakit($tanggalawal,$tanggalakhir)
    {
        $query = $this->db->query("SELECT * FROM record_perizinan_pengasuhan WHERE create_at BETWEEN '$tanggalawal' AND '$tanggalakhir' HAVING nama_perizinan = 'Perizinan Sakit'");
        return $query->num_rows();
    }

    function filter_by_tanggal_pulang_sementara($tanggalawal,$tanggalakhir)
    {
        $query = $this->db->query("SELECT * FROM record_perizinan_pengasuhan WHERE create_at BETWEEN '$tanggalawal' AND '$tanggalakhir' HAVING nama_perizinan = 'Perizinan Pulang Sementara'");
        return $query->num_rows();
    }

   
}

    