<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Daftartinggal extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Siswa_model');
        $this->load->model('Kategori_model');
        $this->load->model('Bakes_riwayat_sakit_model');

        // cek user login
        check_login();
    }

    /*
     * Listing of emergency1
     */
    function tabel_emergency1()
    {
        $data['santri_sakit'] = $this->Bakes_riwayat_sakit_model->get_aktif_emergency1();

        $data['_view'] = 'bakes/daftartinggal/tabel_aktif_emergency1';

        $this->load->view('template/header', $data);
        $this->load->view('template/sidebar', $data);
        $this->load->view('bakes/daftartinggal/tabel_aktif_emergency1', $data);
        $this->load->view('template/footer', $data);
    }

    /*
     * Listing of emergency2
     */
    function tabel_emergency2()
    {
        $data['santri_sakit'] = $this->Bakes_riwayat_sakit_model->get_aktif_emergency2();

        $data['_view'] = 'bakes/daftartinggal/tabel_aktif_emergency2';

        $this->load->view('template/header', $data);
        $this->load->view('template/sidebar', $data);
        $this->load->view('bakes/daftartinggal/tabel_aktif_emergency2', $data);
        $this->load->view('template/footer', $data);
    }

    /*
     * Listing of rumah sakit
     */
    function tabel_rumahsakit()
    {
        $data['santri_sakit'] = $this->Bakes_riwayat_sakit_model->get_aktif_rumahsakit();

        $data['_view'] = 'bakes/daftartinggal/tabel_aktif_rumahsakit';

        $this->load->view('template/header', $data);
        $this->load->view('template/sidebar', $data);
        $this->load->view('bakes/daftartinggal/tabel_aktif_rumahsakit', $data);
        $this->load->view('template/footer', $data);
    }

}
