<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Riwayatsakit extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Siswa_model');
        $this->load->model('Kategori_model');
        $this->load->model('Bakes_riwayat_sakit_model');

        // cek user login
        check_login();
    }

    /*
     * Listing of tabel data santri
     */
    function index()
    {
        // ambil data santri aktif
        $data['siswa'] = $this->Siswa_model->get_aktif_siswa();

        $data['_view'] = 'bakes/riwayatsakit/index';

        $this->load->view('template/header', $data);
        $this->load->view('template/sidebar', $data);
        $this->load->view('bakes/riwayatsakit/index', $data);
        $this->load->view('template/footer', $data);
    }

    /*
     * Listing of detail riwayat sakit siswa
     */
    function detail ($id)
    {
        // periksa bahwa data santri itu ada
        $data['siswa'] = $this->Siswa_model->get_siswa($id);

        if (isset($data['siswa']['id'])) {
                $data['datafilter'] =$this->Bakes_riwayat_sakit_model->filter_by_id_siswa($id);
                $data['detail'] =$this->Siswa_model->detail_data($id);
             
                $data['_view'] = 'bakes/riwayatsakit/detail';
                $this->load->view('template/header', $data);
                $this->load->view('template/sidebar', $data);
                $this->load->view('bakes/riwayatsakit/detail', $data);
                $this->load->view('template/footer', $data);
        } else
        show_error('The siswa you are trying to edit does not exist.');
    }

    /*
     * Function for input riwayat sakit siswa
     */
    function input_riwayatsakit($id)
    {
        // periksa bahwa data santri itu ada
        $data['siswa'] = $this->Siswa_model->get_siswa($id);
        // munculkan detail data santri
        $data['detail'] = $this->Siswa_model->detail_data($id);

        if(isset($data['siswa']['id']))
        {
            $this->load->library('form_validation');
			$this->form_validation->set_rules('jenis_penyakit','Jenis Penyakit','required');

            if($this->form_validation->run()) {
               
                $id_siswa =  $this->input->post('id_siswa');
                $id_penginput = $this->input->post('penginput');
                $nama_lengkap = $this->input->post('nama_lengkap');
                $jenis_penyakit = $this->input->post('jenis_penyakit');
                $kategori_penyakit = $this->input->post('kategori');
                $tindakan = $this->input->post('tindakan');
                $status = $this->input->post('status');
                $keterangan = $this->input->post('keterangan');
        
        
                $data = array(
                    'id_siswa' => $id_siswa,
                    'id_penginput' => $id_penginput,
                    'jenis_penyakit' => $jenis_penyakit,
                    'kategori_penyakit' => $kategori_penyakit,
                    'tindakan' => $tindakan,
                    'status' => $status,
                    'keterangan' => $keterangan,);
                    
        
                $this->Bakes_riwayat_sakit_model->tambah_riwayatsakit($data);
                $this->session->set_flashdata('berhasil', 'Anda berhasil menambahkan data riwayat sakit <strong>' . $nama_lengkap . '</strong>' . ' berupa <strong>' . $jenis_penyakit . '</strong>' );
                redirect('bakes/riwayatsakit');
            }
            else
            {
                $data['sakitbiasa'] = $this->Kategori_model->get_penyakit_biasa();
                $data['sakitsedang'] = $this->Kategori_model->get_penyakit_sedang();
                $data['sakitmenular'] = $this->Kategori_model->get_penyakit_menular();
                $data['stafbakes'] = $this->Kategori_model->get_staf_bakes();
                $data['stafbakeskelas6'] = $this->Kategori_model->get_staf_bakes_kelas6();

                $data['_view'] = 'bakes/riwayatsakit/input_riwayat_sakit';
                $this->load->view('template/header');
                $this->load->view('template/sidebar');
                $this->load->view('bakes/riwayatsakit/input_riwayat_sakit', $data);
                $this->load->view('template/footer');
            }
        }
        else
            show_error('The Riwayat Sakit Santri you are trying to input does not exist.');
    }

    /*
     * Function for Editing a riwayat sakit santri
     */
    function edit_riwayatsakit($id_riwayatsakit)
    {   
        // check if the riwayat sakit exists before trying to edit it
        $data['riwayatsakit'] = $this->Bakes_riwayat_sakit_model->get_riwayatsakit($id_riwayatsakit);

        if(isset($data['riwayatsakit']['id_sakit']))
        {
            $this->load->library('form_validation');
			$this->form_validation->set_rules('jenis_penyakit','Jenis Penyakit','required');

            $id_sakit = $data['riwayatsakit']['id_sakit'];
            $id_siswa = $data['riwayatsakit']['id_siswa'];
            $data['detail'] = $this->Siswa_model->detail_data($id_siswa);
		
			if($this->form_validation->run())     
            {   
                $params = array(
                    'id_penginput' => $this->input->post('penginput'),
                    'tindakan' => $this->input->post('tindakan'),
                    'status' => $this->input->post('status'),
                    'keterangan' => $this->input->post('keterangan'),
                );

                $nama_siswa = $this->input->post('nama_lengkap');

                $this->Bakes_riwayat_sakit_model->update_riwayatsakit($id_riwayatsakit,$params);
                $this->session->set_flashdata('berhasil', 'Anda berhasil mengubah data riwayat sakit <strong>' . $nama_siswa . '</strong>' . ' menjadi <strong>' . ($this->input->post('status') == 1 ? 'Masih Dirawat' : 'Sudah Sembuh') . '</strong>');

                redirect(base_url('bakes/riwayatsakit/detail/' . $id_siswa)) ;
            }
            else
            {
                $data['stafbakes'] = $this->Kategori_model->get_staf_bakes();
                $data['stafbakeskelas6'] = $this->Kategori_model->get_staf_bakes_kelas6();

                $data['_view'] = 'bakes/riwayatsakit/edit_riwayatsakit';
                $this->load->view('template/header',$data);
                $this->load->view('template/sidebar',$data);
                $this->load->view('bakes/riwayatsakit/edit_riwayatsakit',$data);
                $this->load->view('template/footer',$data);
            }
        }
        else
            show_error('The Riwayat Sakit Santri you are trying to edit does not exist.');
    }

    /*
     * Function of hapus riwayat sakit siswa
     */
    function hapus_riwayatsakit($id_riwayatsakit)
    {
        // check if the riwayat sakit exists before trying to edit it
        $data['riwayatsakit'] = $this->Bakes_riwayat_sakit_model->get_riwayatsakit($id_riwayatsakit);

        if(isset($data['riwayatsakit']['id_sakit']))
        {
            $this->Bakes_riwayat_sakit_model->delete_riwayatsakit($id_riwayatsakit);
            $this->session->set_flashdata('hapus', 'Anda berhasil menghapus data riwayat sakit <strong>' .  $data['riwayatsakit']['nama_lengkap'] . '</strong>' . ' berupa <strong>' .  $data['riwayatsakit']['jenis_penyakit'] . '</strong>' );
            redirect(base_url('bakes/riwayatsakit/detail/' . $data['riwayatsakit']['id_siswa'])) ;
        } else
        show_error('The siswa you are trying to delete does not exist.');
    }
    
    /*
     * Function of print pdf pelanggaran siswa
     */
    function print()
    {
        $id_siswa = $this->input->post('id_siswa');
        $filterid = $this->input->post('print');

        if ($filterid == 1) {
            $data['datafilter'] =$this->Bakes_riwayat_sakit_model->filter_by_id_siswa($id_siswa);
            $data['detail'] =$this->Siswa_model->detail_data($id_siswa);
        
            $data['_view'] = 'bakes/riwayatsakit/print_laporan';
 
            $this->load->view('bakes/riwayatsakit/print_laporan', $data);
            $this->load->view('template/footer', $data);
        }
    }

    /*
     * Listing of form Filter pelanggaran siswa
     */
    function form_filter_tanggal ()
    {
        $this->load->view('template/header');
        $this->load->view('template/sidebar');
        $this->load->view('bakes/riwayatsakit/form_filter_tanggal');
        $this->load->view('template/footer');
    }
   
    /*
     * Function of Submit form Filter pelanggaran siswa
     */
    function filterbytanggal()
    {
        $tanggalawal = $this->input->post('tanggalawal');
        $tanggalakhir = $this->input->post('tanggalakhir');
        $nilaitanggal = $this->input->post('nilaitanggal');

           
        if ($nilaitanggal == 1) {

            $data['tanggalawal'] = $tanggalawal;
            $data['tanggalakhir'] = $tanggalakhir;

            $data['datademam'] =$this->Bakes_riwayat_sakit_model->filter_by_tanggal_demam($tanggalawal,$tanggalakhir);
            $data['datapusing'] =$this->Bakes_riwayat_sakit_model->filter_by_tanggal_pusing($tanggalawal,$tanggalakhir);
            $data['datamuntaber'] =$this->Bakes_riwayat_sakit_model->filter_by_tanggal_muntaber($tanggalawal,$tanggalakhir);
            $data['datamencret'] =$this->Bakes_riwayat_sakit_model->filter_by_tanggal_mencret($tanggalawal,$tanggalakhir);

            $data['datatipes'] =$this->Bakes_riwayat_sakit_model->filter_by_tanggal_tipes($tanggalawal,$tanggalakhir);
            $data['datapatahtulang'] =$this->Bakes_riwayat_sakit_model->filter_by_tanggal_patahtulang($tanggalawal,$tanggalakhir);

            $data['datascabies'] =$this->Bakes_riwayat_sakit_model->filter_by_tanggal_scabies($tanggalawal,$tanggalakhir);
            $data['datacacar'] =$this->Bakes_riwayat_sakit_model->filter_by_tanggal_cacar($tanggalawal,$tanggalakhir);
          
    
            $this->load->view('template/header', $data);
            $this->load->view('template/sidebar', $data);
            $this->load->view('bakes/riwayatsakit/print_grafik', $data);
            $this->load->view('template/footer', $data);
    
        }
    }

     /*
     * Listing Of Input Massal
     */
    function input_massal()
    {   
        $data['siswa'] = $this->Siswa_model->get_aktif_siswa();

        $data['sakitbiasa'] = $this->Kategori_model->get_penyakit_biasa();
        $data['sakitsedang'] = $this->Kategori_model->get_penyakit_sedang();
        $data['sakitmenular'] = $this->Kategori_model->get_penyakit_menular();
        $data['stafbakes'] = $this->Kategori_model->get_staf_bakes();
        $data['stafbakeskelas6'] = $this->Kategori_model->get_staf_bakes_kelas6();

        $this->load->view('template/header',$data);
        $this->load->view('template/sidebar',$data);
        $this->load->view('bakes/riwayatsakit/input_massal',$data);
        $this->load->view('template/footer',$data);
    }
    
     /*
     * Function for Submit Input Massal
     */
    function simpan_massal()
    {
        $result = $this->input->post('id_siswa[]');

        $params = array();
        $jenis_penyakit = $this->input->post('jenis_penyakit');
        $kategori_penyakit = $this->input->post('kategori');
        $id_penginput = $this->input->post('penginput');
        $tindakan = $this->input->post('tindakan');
        $status = $this->input->post('status');
        $keterangan = $this->input->post('keterangan');

        foreach($result as $result){
            
            // $result_explode = explode('|', $result);
            // $id_siswa = $result_explode[0];
            // $nama_lengkap = $result_explode[1];
            $id_siswa = $result;

            array_push($params, [
                'jenis_penyakit' => $jenis_penyakit,
                'kategori_penyakit' => $kategori_penyakit,
                'id_penginput' => $id_penginput,
                'tindakan' => $tindakan,
                'status' => $status,
                'keterangan' => $keterangan,
                'id_siswa' => $id_siswa
            ]);

        $jumlahdata = count($params); 

        $this->session->set_flashdata('berhasil', 'Anda berhasil menambahkan data pelanggaran <strong>'.$jenis_penyakit.'</strong> sejumlah <strong>'.$jumlahdata.' Santri </strong>');
        }

        $this->db->insert_batch('record_riwayat_sakit_santri', $params);
        redirect('bakes/riwayatsakit/');
    }

    /*
     * Listing of newest pelanggaran siswa
     */
    function tabel_riwayatsakit()
    {
        $data['pelanggaran_siswa'] = $this->Bakes_riwayat_sakit_model->get_tabel_riwayatsakit_siswa();

        $data['_view'] = 'bakes/riwayatsakit/tabel_indeks_riwayatsakit';

        $this->load->view('template/header', $data);
        $this->load->view('template/sidebar', $data);
        $this->load->view('bakes/riwayatsakit/tabel_indeks_riwayatsakit', $data);
        $this->load->view('template/footer', $data);
    }

    /*
     * Listing of filter pelanggaran siswa
     */
    function filter ()
    {

        $data['sakitbiasa'] = $this->Kategori_model->get_penyakit_biasa();
        $data['sakitsedang'] = $this->Kategori_model->get_penyakit_sedang();
        $data['sakitmenular'] = $this->Kategori_model->get_penyakit_menular();
        $data['stafbakes'] = $this->Kategori_model->get_staf_bakes();
        $data['stafbakeskelas6'] = $this->Kategori_model->get_staf_bakes_kelas6();
        $data['rayon'] = $this->Kategori_model->get_rayon();

        $this->load->view('template/header');
        $this->load->view('template/sidebar');
        $this->load->view('bakes/filter/index', $data);
        $this->load->view('template/footer');
    }

    /*
     * Function for Submit Filter Perkategori
     */
    function filterbykategori()
    {
        $jenis_penyakit = $this->input->post('jenis_penyakit');
        $tindakan = $this->input->post('tindakan');
        $penginput = $this->input->post('penginput');

        $tanggalawal = $this->input->post('tanggalawal');
        $tanggalakhir = $this->input->post('tanggalakhir');
        $rayon = $this->input->post('rayon');

        $nilaisakit = $this->input->post('nilaisakit');
        $nilaitindakan = $this->input->post('nilaitindakan');
        $nilaipenginput = $this->input->post('nilaipenginput');
        
        $nilaitanggal = $this->input->post('nilaitanggal');
        $nilairayon = $this->input->post('nilairayon');
    
        if ($nilaisakit == 1) {
            $data['title'] = "Data Santri Yang Sakit $jenis_penyakit";
            $data['datafilter'] =$this->Bakes_riwayat_sakit_model->filter_by_penyakit($jenis_penyakit);
   
            $this->load->view('bakes/filter/print_laporan', $data);
            $this->load->view('template/footer', $data);
    
        }

        if ($nilaitindakan == 1) {
            $data['title'] = "Data Santri Yang Mendapat Tindakan $tindakan";
            $data['datafilter'] =$this->Bakes_riwayat_sakit_model->filter_by_tindakan($tindakan);
    
            $this->load->view('bakes/filter/print_laporan', $data);
            $this->load->view('template/footer', $data);
    
        }

        if ($nilaipenginput == 1) {
            $data['title'] = "Data Santri Yang Diinput Oleh $penginput";
            $data['datafilter'] =$this->Bakes_riwayat_sakit_model->filter_by_penginput($penginput);
    
            $this->load->view('bakes/filter/print_laporan', $data);
            $this->load->view('template/footer', $data);
    
        }

        if ($nilaitanggal == 1) {
            $data['title'] = "Data Santri Yang Sakit Dari $tanggalawal Sampai $tanggalakhir" ;
            $data['datafilter'] =$this->Bakes_riwayat_sakit_model->filter_by_tanggal($tanggalawal,$tanggalakhir);
    
            $this->load->view('bakes/filter/print_laporan', $data);
            $this->load->view('template/footer', $data);
    
        }

        if ($nilairayon == 1) {
            $data['title'] = "Data Santri Yang Sakit Dari Rayon $rayon";
            $data['datafilter'] =$this->Bakes_riwayat_sakit_model->filtersakit_by_rayon($rayon);
    
            $this->load->view('bakes/filter/print_laporan', $data);
            $this->load->view('template/footer', $data);
    
        }
    }

    /*
     * Javasript autofill Kategori Penyakit
     */
    function fill_kategori_penyakit(){
        $jenis_penyakit = $_POST['jenis_penyakit'];
        $s = "SELECT kategori as kategori FROM tb_jenis_penyakit WHERE nama_penyakit='$jenis_penyakit'";

        $res = $this->db->query($s)->row_array();
        echo json_encode($res);
    }

    //////////////////////////////////////////////////// FUNGSI UNTUK TABEL PELANGGARAN ////////////////////////////////////////////////////////////////

    /*
     * Function for Editing a riwayat sakit santri
     */
    function edit_riwayatsakit_tabel($id_riwayatsakit)
    {   
       // check if the riwayat sakit exists before trying to edit it
       $data['riwayatsakit'] = $this->Bakes_riwayat_sakit_model->get_riwayatsakit($id_riwayatsakit);

       if(isset($data['riwayatsakit']['id_sakit']))
       {
           $this->load->library('form_validation');
           $this->form_validation->set_rules('jenis_penyakit','Jenis Penyakit','required');

           $id_sakit = $data['riwayatsakit']['id_sakit'];
           $id_siswa = $data['riwayatsakit']['id_siswa'];
           $data['detail'] = $this->Siswa_model->detail_data($id_siswa);
       
           if($this->form_validation->run())     
           {   
               $params = array(
                   'id_penginput' => $this->input->post('penginput'),
                   'tindakan' => $this->input->post('tindakan'),
                   'status' => $this->input->post('status'),
                   'keterangan' => $this->input->post('keterangan'),
               );

               $nama_siswa = $this->input->post('nama_lengkap');

               $this->Bakes_riwayat_sakit_model->update_riwayatsakit($id_riwayatsakit,$params);
               $this->session->set_flashdata('berhasil', 'Anda berhasil mengubah data riwayat sakit <strong>' . $nama_siswa . '</strong>' . ' menjadi <strong>' . ($this->input->post('status') == 1 ? 'Masih Dirawat' : 'Sudah Sembuh') . '</strong>');

               redirect(base_url('bakes/riwayatsakit/tabel_riwayatsakit')) ;
           }
           else
           {
               $data['stafbakes'] = $this->Kategori_model->get_staf_bakes();
               $data['stafbakeskelas6'] = $this->Kategori_model->get_staf_bakes_kelas6();

               $data['_view'] = 'bakes/riwayatsakit/edit_riwayatsakit_tabel';
               $this->load->view('template/header',$data);
               $this->load->view('template/sidebar',$data);
               $this->load->view('bakes/riwayatsakit/edit_riwayatsakit_tabel',$data);
               $this->load->view('template/footer',$data);
           }
       }
       else
           show_error('The Riwayat Sakit Santri you are trying to edit does not exist.');
    } 

    /*
     * Function of hapus riwayat sakit siswa
     */
    function hapus_riwayatsakit_tabel($id_riwayatsakit)
    {
        // check if the riwayat sakit exists before trying to edit it
       $data['riwayatsakit'] = $this->Bakes_riwayat_sakit_model->get_riwayatsakit($id_riwayatsakit);

        if(isset($data['riwayatsakit']['id_sakit']))
        {
            $this->Bakes_riwayat_sakit_model->delete_riwayatsakit($id_riwayatsakit);
            $this->session->set_flashdata('hapus', 'Anda berhasil menghapus data riwayat sakit <strong>' .  $data['riwayatsakit']['nama_lengkap'] . '</strong>' . ' berupa <strong>' .  $data['riwayatsakit']['jenis_penyakit'] . '</strong>' );
            redirect(base_url('bakes/riwayatsakit/tabel_riwayatsakit')) ;
        } else
        show_error('The siswa you are trying to delete does not exist.');
    }

}
